#!/bin/sh
#comment \
export DISPLAY=$4 ; host=$1;port=$2 ;pid=$3 ; exec wish "$0" "$@" 
set host [lindex $argv 0]
set port [lindex $argv 1]
set pid [lindex $argv 2]
source /home/wfs/gcl-2.3/gcl-tk/decode.tcl
GclAnswerSocket $host $port $pid




