@c  Copyright (c) 1994 William Schelter.

@node C Interface, System Definitions, GCL Specific, Top
@chapter C Interface

@menu
* Available Symbols::		
@end menu

@node Available Symbols,  , C Interface, C Interface
@section Available Symbols

When GCL is built, those symbols in the system libraries which
are referenced by functions linked in in the list of objects
given in @file{unixport/makefile}, become available for reference
by GCL code.

On some systems it is possible with @code{faslink} to load @file{.o} files
which reference other libraries, but in general this practice is not
portable.







