

XS(string_register->st.st_fillp);
XS(string_register->st.st_fillp);
XS(string_register->st.st_dim);
XS(string_register->st.st_self);
XS(token->st.st_fillp);
XS(in_signal_handler);
XS(nlj_active);
XS(nlj_fr);
XS(nlj_tag);
XS(CMPtemp);
XS(CMPtemp1);
XS(CMPtemp2);
XS(CMPtemp3);
XS(FIXtemp);
XS(PRINTarray);
XS(PRINTbase);
XS(PRINTcase);
XS(PRINTcircle);
XS(PRINTescape);
XS(PRINTgensym);
XS(PRINTlength);
XS(PRINTlevel);
XS(PRINTpackage);
XS(PRINTpretty);
XS(PRINTradix);
XS(PRINTstream);
XS(PRINTstructure);
XS(PRINTvs_limit);
XS(PRINTvs_top);
XS(READbase);
XS(READdefault_float_format);
XS(READsuppress);
XS(READtable);
XS(ctl_end);
XS(ctl_index);
XS(ctl_origin);
XS(endp_temp);
XS(eval1);
XS(line_length);
XS(in_list_flag);
XS(kf);
XS(tf);
XS(left_trim);
XS(right_trim);
XS(lex_env);
XS(key_function);
XS(test_function);
XS(item_compared);
XS(intern_flag);
XS(printStructBufp);
XS(sfaslp);
XS(preserving_whitespace_flag);
XS(sharing_table);
XS(string_sign);
XS(string_boundary);
XS(car_or_cdr);
XS(casefun);
XS(tmp_alloc);
#ifndef GMP 
#ifdef CMAC
XS(s4_neg_int[3]);
XS(small_neg_int[2]);
XS(small_pos_int[2]);
#endif
XS(overflow);
XS(top);
XS(hiremainder);
XS(in_saved_avma);
XS(avma	);
#endif

/*  put in NO_INTERRUPT
YS(fmt_base);
YS(fmt_end);
YS(fmt_indents);
YS(fmt_index);
YS(fmt_jmp_buf);
YS(fmt_line_length);
YS(fmt_nparam);
YS(fmt_paramp);
YS(fmt_spare_spaces);
YS(fmt_stream);
YS(fmt_string);
YS(fmt_temporary_stream);
YS(fmt_temporary_string);
 */
