#!/bin/sh
OTHER=/rascal/public/akcl

for v in lsp/*.lsp cmpnew/*.lsp cmpnew/*.lisp ;
do
if  cmp $v ${OTHER}/$v  ; then true ; else ls -l $v ${OTHER}/$v; fi
done

for v in c/*.c c/*.d  unixport/*.c;
do
if  cmp $v ${OTHER}/$v  ; then true ; else ls -l $v ${OTHER}/$v; fi
done

for v in `echo doc/* xbin/* | sed -e "/~/d"` -e "/emacs-path/d" -e "/xbin\/kcl/d" ;
do
if  cmp $v ${OTHER}/$v  ; then true ;else ls -l $v ${OTHER}/$v; fi
done


