#!/bin/sh
FILE=$1
KCL=${HOME}/akcl/unixport/saved_kcl
# the (start address) you observe while running stand alone.
ADDR=92000
ld -d -N -x -A ${KCL} -R 92000 $1 -o /tmp/ldtest
a.out $1 ${HOME}/akcl/unixport/saved_kcl ${HOME}/akcl/unixport/ 
if
comp /tmp/ldtest /tmp/sfasltest
then 
echo $1 differed
else
echo $1 ok
fi


