#!/bin/sh
OBJS=`find ./ \( -type f -o -type l \) -a -print  | sed -e "/~/d" -e "/#/d" -e "/.*\.o/d"   -e "/.*TAGS/d"  -e "/standard-kcl/d" -e "/core/d" -e "/saved/d" -e "/raw/d"  -e "/rsym$/d" -e "/merge$/d" -e "/dpp$/d" -e "/-$/d" -e "/installed_kcl/d"    -e "/^[^V]*\/cmpinclude.h/d" -e "/config\.h/d" -e "/_aos/d" -e  "/gazonk/d" -e "/\.out/d"  -e "/print_doc$/d"  -e "/foo/d" -e "/akcllib/d" -e "/\.fn/d" -e "/collectfn.[cdh]/d" -e "/Vmakefile/d" -e "/ps2_/d"  -e "/.*\.a$/d"   -e "/test\//d" -e "/tmpx/d" -e "/V\//d" -e "/xbin\//d" -e "/mpi-386.s/d" `

rm -f unixport/akcldos.lsp
(cd unixport ; make -f makefile.dos "CC=gcc -DVOL=volatile " AKCLDIR=/akcl akcldos.lsp)

OTHERS="xbin/*.bat  tmpxx_.tem"
echo ${OBJS} ${OTHERS} 
rm -f ${HOME}/tmp/akclsrc.zip 
zip  -p ${HOME}/tmp/akclsrc.zip  ${OBJS} ${OTHERS}

# get a patched h/cmpinclude.h 
./xbin/file-sub h/dos-go32.h h/cmpinclude.h "Begin for cmpinclud" "End for cmpinclud"

if [ -d /tmp/h ] ; then true ; else mkdir /tmp/h ; fi
mv tmpx /tmp/h/cmpinclude.h
cd /tmp
zip -p ${HOME}/tmp/akclsrc.zip h/cmpinclude.h
rm -f h/cmpinclude.h


