#!/bin/sh
for v in $@ ; do
echo
echo '/*' for  file $v '*/'
echo 
grep ":OF" $v > tmpx.c
gcc -E tmpx.c | sed -e '/# [0-9]/d' -e '/  static /d' \
	-e "s:\\((.*)\\):GPR(\\1);:g" -e "s:va_list ap:...:g" -e "s:  extern :extern :g"

done

