#!/bin/sh
cd V
OBJS=`find . \( -name '*[0-9a-zA-Z]' -a  -type f \) -print`
MAINDIR=/public/kcl
cd ..

for v in ${OBJS} ; do
./merge  ${MAINDIR}/$v V/$v  tmpx
if
cmp $v tmpx > /dev/null
then true
# else echo $v differed do
else
echo kcl-merge $v
# echo ./merge  ${MAINDIR}/$v V/$v  tmpx
# ls -l tmpx $v
# diff -c tmpx $v
fi
done

rm tmpx

OBJS=`find ./c \( -name '[./0-9a-zA-Z]*.[cd]' -a  -type f \) -print`
LOBJ=`find ./lsp \( -name '[./0-9a-zA-Z]*.lsp' -a  -type f \) -print`  
CMPOBJ=`find ./cmpnew \( -name '[./0-9a-zA-Z]*.lsp' -a  -type f \) -print`
HFIL=`find ./h \( -name '[./0-9a-zA-Z]*.h' -a  -type f \) -print`

for v in ${OBJS} ${LOBJ} ${CMPOBJ} ${HFIL} ;
do if  [ -f ${MAINDIR}/$v ]
   then
    if  cmp $v ${MAINDIR}/$v > /dev/null 
     then true
     else
      if [ ! -f V/$v ] ; then  echo kcl-merge $v ;  fi
    fi
   fi
done
