#!/bin/sh

if [ $# -eq 3 ] ; then MOVE=$1 ; shift 1; else MOVE=ln;fi

F1=$1
F2=$2


if [ $# -ge 2 ] && [ -f $2 ] && cmp $1 $2 > /dev/null
then  echo $1 and $2  are identical ;
else
echo $1 and $2 were not the same.
rm -f $2
${MOVE} $1 $2
echo ln $1 $2
fi

