#!/bin/sh

#rm -f tmpx
#for v in `cat unixport/lspboots unixport/cmpboots` ;
#do echo "/$v.[chd]/d" >>tmpx
#done
HERE=$1
GCL_VERS=$2
echo > ${HERE}/tmpx
GCL=`basename ${HERE}`
OBJS=`find ./${GCL} \( -type f  \) -a -print  | sed  -f ${HERE}/tmpx  -e "/notyet/d" -e "s:/${GCL}/:/${GCL_VERS}/:g" -e "/~/d" -e "/#/d" -e "/.*\.o/d"   -e "/TAGS$/d" -e "/tags$/d"  -e "/standard-gcl/d" -e "/core/d" -e "/saved_/d" -e "/unixport\/raw/d"  -e "/rsym$/d" -e "/merge$/d" -e  "/errs$/d" -e "/dpp$/d" -e "/-$/d" -e "/installed_gcl/d"  -e '/\/\.nfs/d'  -e "/config\.h/d" -e "/_aos/d" -e  "/gazonk/d" -e "/\.out$/d"  -e "/print_doc$/d"  -e "/foo/d" -e "/gcllib/d" -e "/\.fn$/d" -e "/collectfn.[cdh]/d"  -e "/ps2_/d"  -e "/.*\.a$/d"   -e "/test\//d" -e "/tmpx/d" -e "/makedefs$/d"   -e "/\.tgz/d" -e "/\/old\//d"  -e "/guis$/d" -e "/\.X$/d"  -e "/gcltkaux/d" -e "/\.dvi/d" -e "/\.log/d" -e '/\.aux$/d'  -e "/\.exe$/d"  -e "/grab_defs$/d" -e "/config.status/d" -e "/config.cache/d" -e "/\.rej$/d" -e "/\/CVS\//d" -e '/file-sub$/d' -e '/\.lo$/d' -e '/gmp\/.*\/Makefile$/d' -e '/\.libs/d' -e /makedefsafter/d `
rm -f ${HERE}/tmpx
echo ${OBJS}






