#!/bin/sh

# Send in a notification about successful compilation, which may
# help others, and help in determining on which machines and
# levels of the OS compilation has been successful.

if [ -f /bin/mail ] ; then

 echo GCL `cat majvers`.`cat minvers` Machine: `cat machine`   > tmpx
 ls -l h/config.h >> tmpx
 echo $@ >> tmpx

 if fgrep gcc tmpx > /dev/null ; then
  gcc -v 2>> tmpx
 fi
  
 if [ -f /etc/motd ] ; then
  cat /etc/motd | sed -e "2,10000d" >> tmpx ;
 fi
# if you are wfs dont bother mailing 
 if [ "${HOME}" = "/home/wfs" ] ; then true ; else
 cat tmpx | /bin/mail gcl@math.utexas.edu
 fi
fi


