#!/bin/sh
TMP=$1
TEST=$2
NQTHM=$3


if [ -d ${TMP} ] ; then rm -f ${TMP}/* ; else mkdir ${TMP} ;fi
	ln -s `pwd`/xbin/kcl ${TMP}
	ln -s ${HOME}/little.lisp ${TMP}
	(cd ${NQTHM} ; ln -s `pwd`/*.lisp ${TMP})

exit 0

