#!/bin/sh
TAR=${HOME}/tmp/gcl.tgz
xbin/distribute ${TAR}

if [ "$1" = "" ] ; then
   make -f xbin/maketest make "TAR=${TAR}"
else
if [ "$1" = "fireant.ma.utexas.edu" ] ; then true; else
   rcp ${TAR}  $1:tmp/${TAR} ;fi 
   rcp xbin/test1 $1:tmp
   rsh $1 '(cd tmp ; test1 ${HOME} ${HOME}/tmp/gcl.tgz)' < /dev/null
fi




