#!/bin/sh
TEST=$1
TAR=$2
echo Using tar file ${TAR} in directory ${TEST}/tmp/akcl


	 if [ ! -d ${TEST} ] ; then mkdir ${TEST} ;fi
	 if [ ! -d ${TEST}/tmp ] ; then mkdir ${TEST}/tmp ;fi
	 (cd ${TEST}/tmp ;rm -r -f akcl ; mkdir akcl; cd akcl ;uncompress -c ${TAR} | tar xvf -)
	 (cd  ${TEST}/tmp/akcl ; echo Now in `pwd`; \
	 if [ "`hostname`" = fireant.ma.utexas.edu ] ; \
	  then ./add-defs sun4 ; else \
	if [ "`hostname`" = "nicolas.ma.utexas.edu" ] ; \
	  then ./add-defs hp300-bsd ; \
		else add-defs sun3-os4 \
            ;fi ;fi)
(cd ${TEST}/tmp/akcl ; make -f Smakefile -e "SU=SKIP" )
(cd ${TEST}/tmp/akcl ; make -f xbin/maketest "LISP=${TEST}/tmp/akcl/xbin/kcl")

