
(IN-PACKAGE "PCL") 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FUNCTION) METHOD-CALL-FUNCTION CACHE-LIMIT-FN
            FAST-METHOD-CALL-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FIXNUM) EARLY-CLASS-SIZE CPD-COUNT
            CHECKING-LIMIT-FN N-N-ACCESSORS-LIMIT-FN
            ARG-INFO-NUMBER-REQUIRED ONE-INDEX-LIMIT-FN
            DEFAULT-LIMIT-FN PV-CACHE-LIMIT-FN
            FAST-INSTANCE-BOUNDP-INDEX PV-TABLE-PV-SIZE CACHE-COUNT
            CACHING-LIMIT-FN)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM) T) POWER-OF-TWO-CEILING)) 
(PROCLAIM '(FTYPE (FUNCTION (T) FIELD-TYPE) CACHE-FIELD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) LIST) PV-TABLE-CALL-LIST
            PV-TABLE-SLOT-NAME-LISTS CACHE-OVERFLOW)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (MEMBER NIL T)) CACHE-VALUEP)) 
(PROCLAIM '(FTYPE (FUNCTION (T) SIMPLE-VECTOR) CACHE-VECTOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (VALUES T T)) MAKE-KEYWORD
            MAKE-CLASS-PREDICATE-NAME)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T) T) %CCLOSURE-ENV-NTHCDR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM FIXNUM T) FIXNUM)
            COMPUTE-PRIMARY-CACHE-LOCATION)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 256)) CACHE-NKEYS)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 512)) CACHE-LINE-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (OR CACHE NULL)) PV-TABLE-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *)
            |(FAST-METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
            |(FAST-METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
            |(FAST-METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES (GENERIC-FUNCTION T))|
            |(FAST-METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
            |(FAST-METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
            |(FAST-METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
            |(FAST-METHOD DEFAULT-INITARGS (SLOT-CLASS T))|
            ACCESSOR-MISS |(FAST-METHOD MAKE-INSTANCE (SYMBOL))|
            |(FAST-METHOD DESCRIBE-OBJECT (CLASS T))|
            |(FAST-METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
            |(FAST-METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
            |(FAST-METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
            |(FAST-METHOD DESCRIBE-OBJECT (T T))|
            |(FAST-METHOD NO-APPLICABLE-METHOD (T))|
            SET-CLASS-SLOT-VALUE-1 GENERATE-DISCRIMINATION-NET
            ACCESSOR-VALUES MAKE-FINAL-CHECKING-DFUN
            MAKE-FINAL-ONE-INDEX-ACCESSOR-DFUN
            MAKE-ONE-CLASS-ACCESSOR-DFUN BOOTSTRAP-ACCESSOR-DEFINITION
            GET-ACCESSOR-FROM-SVUC-METHOD-FUNCTION
            GET-ACCESSOR-METHOD-FUNCTION
            INITIALIZE-INSTANCE-SIMPLE-FUNCTION
            MAKE-SHARED-INITIALIZE-FORM-LIST EMIT-CHECKING-OR-CACHING
            REAL-MAKE-METHOD-LAMBDA EMIT-CHECKING-OR-CACHING-FUNCTION
            SETF-SLOT-VALUE-USING-CLASS-DFUN ORDER-SPECIALIZERS
            |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (SLOT-CLASS T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (SLOT-CLASS))|
            |(FAST-METHOD DOCUMENTATION (STANDARD-SLOT-DEFINITION))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) *)
            |(FAST-METHOD (SETF SLOT-ACCESSOR-FUNCTION) (T EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD SLOT-VALUE-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD SLOT-VALUE-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-ACCESSOR-METHOD T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
            |(FAST-METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (STANDARD-OBJECT STANDARD-OBJECT))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD :AROUND (GENERIC-FUNCTION METHOD-COMBINATION T))|
            COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO-INTERNAL
            ADD-METHOD-DECLARATIONS MAKE-TWO-CLASS-ACCESSOR-DFUN
            |(FAST-METHOD CHANGE-CLASS (T SYMBOL))| WALK-METHOD-LAMBDA
            |(FAST-METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
            |(FAST-METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
            |(FAST-METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
            |(FAST-METHOD (SETF DOCUMENTATION) (T STANDARD-SLOT-DEFINITION))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *)
            |(FAST-METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
            |(FAST-METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
            |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD METHOD-FUNCTION (STANDARD-METHOD))|
            SLOT-BOUNDP-USING-CLASS-DFUN SLOT-VALUE-USING-CLASS-DFUN
            ITERATE::RENAME-VARIABLES
            |(FAST-METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
            |(FAST-METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
            |(FAST-METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
            |(FAST-METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
            GET-CLASS-SLOT-VALUE-1 ITERATE::EXPAND-INTO-LET
            GENERATING-LISP ITERATE::WALK-GATHERING-BODY CACHING-MISS
            MAKE-FINAL-CONSTANT-VALUE-DFUN MAKE-FINAL-CACHING-DFUN
            MAKE-FINAL-N-N-ACCESSOR-DFUN CONVERT-METHODS
            CHECK-METHOD-ARG-INFO
            GET-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            GET-OPTIMIZED-STD-ACCESSOR-METHOD-FUNCTION
            ACCESSOR-VALUES-INTERNAL CHECKING-MISS CACHE-MISS-VALUES
            ACCESSOR-VALUES1 EMIT-ONE-OR-N-INDEX-READER/WRITER-FUNCTION
            EMIT-READER/WRITER-FUNCTION WALKER::WALK-FORM-INTERNAL
            CONSTANT-VALUE-MISS WALKER::WALK-LET-IF
            OPTIMIZE-SLOT-VALUE-BY-CLASS-P SET-SLOT-VALUE
            |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|
            MAKE-OPTIMIZED-STD-BOUNDP-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-WRITER-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-READER-METHOD-FUNCTION
            EMIT-ONE-OR-N-INDEX-READER/WRITER EMIT-READER/WRITER
            |(FAST-METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
            |(FAST-METHOD CLASS-PROTOTYPE (STD-CLASS))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) *) GET-COMPLEX-INITIALIZATION-FUNCTIONS
            TYPES-FROM-ARGUMENTS MAKE-ACCESSOR-TABLE
            MAKE-FINAL-ACCESSOR-DFUN MAKE-CHECKING-DFUN
            MAKE-N-N-ACCESSOR-DFUN SLOT-VALUE-OR-DEFAULT
            COMPUTE-SECONDARY-DISPATCH-FUNCTION
            MAKE-DEFAULT-INITARGS-FORM-LIST
            GET-SIMPLE-INITIALIZATION-FUNCTION
            GET-EFFECTIVE-METHOD-FUNCTION LOAD-DEFGENERIC
            NESTED-WALK-FORM MAKE-EFFECTIVE-METHOD-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) *) ITERATE::RENAME-LET-BINDINGS
            MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) *)
            |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            GENERATE-DISCRIMINATION-NET-INTERNAL
            CACHE-MISS-VALUES-INTERNAL MEMF-CODE-CONVERTER
            MAKE-LONG-METHOD-COMBINATION-FUNCTION
            MAKE-SHORT-METHOD-COMBINATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) *) MAKE-ONE-INDEX-ACCESSOR-DFUN
            WALKER::WALK-DECLARATIONS GET-SECONDARY-DISPATCH-FUNCTION)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T T T T *) *) REAL-MAKE-A-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) *)
            |(FAST-METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS (STANDARD-OBJECT T T T))|
            ITERATE::ITERATE-TRANSFORM-BODY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) NON-NEGATIVE-FIXNUM) CACHE-SIZE CACHE-MASK
            CACHE-NLINES CACHE-MAX-LOCATION)) 
(PROCLAIM '(FTYPE (FUNCTION (T STREAM T) T) PRINT-DFUN-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T)
            |(FAST-METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
            |(FAST-METHOD UPDATE-GF-DFUN (STD-CLASS T))|
            |(FAST-METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
            |(FAST-METHOD SAME-SPECIALIZER-P (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
            |(FAST-METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
            |(FAST-METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
            |(FAST-METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
            |(FAST-METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
            |(FAST-METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
            |(FAST-METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
            |(FAST-METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
            |(FAST-METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
            |(FAST-METHOD LEGAL-DOCUMENTATION-P (STANDARD-METHOD T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
            |(FAST-METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
            |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD T))|
            |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
            |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD-COMBINATION T))|
            |(FAST-METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
            |(FAST-METHOD PRINT-OBJECT (CLASS T))|
            |(FAST-METHOD PRINT-OBJECT (T T))|
            GET-WRAPPERS-FROM-CLASSES
            |(FAST-METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
            LOAD-LONG-DEFCOMBIN LOAD-SHORT-DEFCOMBIN
            |(FAST-METHOD MAKE-INSTANCE (CLASS))|
            |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
            |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
            |(FAST-METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD VALIDATE-SUPERCLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
            EXPAND-SYMBOL-MACROLET-INTERNAL
            LOAD-PRECOMPILED-DFUN-CONSTRUCTOR
            MAYBE-EXPAND-ACCESSOR-FORM WALKER::WALK-PROG/PROG*
            LOAD-PRECOMPILED-IIS-ENTRY EXPAND-CACHE
            MAKE-EFFECTIVE-METHOD-FUNCTION-TYPE OPTIMIZE-WRITER
            OPTIMIZE-READER FILL-CACHE-P WALKER::WALK-LET/LET*
            WALKER::WALK-TEMPLATE TWO-CLASS-DFUN-INFO
            BOOTSTRAP-SET-SLOT
            EMIT-CHECKING-OR-CACHING-FUNCTION-PRELIMINARY
            FROB-COMBINED-METHOD-ARGS
            MAKE-EFFECTIVE-METHOD-FUNCTION-INTERNAL EXPAND-DEFCLASS
            ADJUST-CACHE WALKER::WALK-BINDINGS-2
            INITIALIZE-INSTANCE-SIMPLE MEMF-TEST-CONVERTER
            WALKER::WALK-DO/DO*
            |(FAST-METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
            |(FAST-METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
            |(FAST-METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
            |(FAST-METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
            |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
            MAKE-EFFECTIVE-METHOD-FUNCTION1 MAKE-DISPATCH-LAMBDA
            |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|
            |(FAST-METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
            |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
            |(FAST-METHOD MAKE-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T))|
            |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (SLOT-CLASS T))|
            |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (SLOT-CLASS T))|
            |(FAST-METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
            |(FAST-METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
            |(FAST-METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND (STRUCTURE-CLASS T))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
            |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
            |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
            |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
            |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
            |(FAST-METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
            |(FAST-METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
            |(FAST-METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
            |(FAST-METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
            |(FAST-METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
            |(FAST-METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
            |(FAST-METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
            |(FAST-METHOD DOCUMENTATION (T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T)
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (DOCUMENTATION-MIXIN T))|
            |(FAST-METHOD COMPUTE-SLOT-ACCESSOR-INFO (EFFECTIVE-SLOT-DEFINITION T T))|
            |(FAST-METHOD (SETF SLOT-ACCESSOR-STD-P) (T EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD SLOT-UNBOUND (T T T))|
            |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD REMOVE-NAMED-METHOD (T T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
            MAKE-EMF-CACHE
            |(FAST-METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
            |(FAST-METHOD FIND-METHOD-COMBINATION (GENERIC-FUNCTION (EQL STANDARD) T))|
            OPTIMIZE-ACCESSOR-CALL OPTIMIZE-GENERIC-FUNCTION-CALL
            BOOTSTRAP-ACCESSOR-DEFINITIONS1 EXPAND-EMF-CALL-METHOD
            LOAD-FUNCTION-GENERATOR MAKE-INSTANCE-FUNCTION-SIMPLE
            GET-MAKE-INSTANCE-FUNCTION-INTERNAL MAKE-FGEN
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT WALKER::WALK-BINDINGS-1
            OPTIMIZE-INSTANCE-ACCESS UPDATE-SLOTS-IN-PV
            MAKE-INSTANCE-FUNCTION-COMPLEX COMPUTE-PV-SLOT
            MAKE-FINAL-ORDINARY-DFUN-INTERNAL
            MAKE-METHOD-INITARGS-FORM-INTERNAL1
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
            |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
            BOOTSTRAP-MAKE-SLOT-DEFINITIONS
            REAL-MAKE-METHOD-INITARGS-FORM
            |(FAST-METHOD WRITER-METHOD-CLASS (SLOT-CLASS T))|
            |(FAST-METHOD READER-METHOD-CLASS (SLOT-CLASS T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
            |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
            |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
            |(FAST-METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
            |(FAST-METHOD (SETF DOCUMENTATION) (T T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T)
            |(FAST-METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
            |(FAST-METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS (EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
            |(FAST-METHOD SLOTS-FETCHER (STANDARD-CLASS))|
            |(FAST-METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
            |(FAST-METHOD GENERIC-FUNCTION-PRETTY-ARGLIST (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
            |(FAST-METHOD SPECIALIZER-CLASS (CLASS))|
            |(FAST-METHOD GF-FAST-METHOD-FUNCTION-P (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD GENERIC-FUNCTION-LAMBDA-LIST (GENERIC-FUNCTION))|
            |(FAST-METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
            |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-WRITER-METHOD))|
            |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-ACCESSOR-METHOD))|
            ITERATE::RENAME-AND-CAPTURE-VARIABLES EMIT-SLOT-READ-FORM
            ENTRY-IN-CACHE-P
            |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
            WALKER::WALK-MULTIPLE-VALUE-BIND DECLARE-STRUCTURE
            SET-FUNCTION-NAME-1 COMPUTE-EFFECTIVE-METHOD PRINT-CACHE
            (SETF PLIST-VALUE) WALKER::WALK-TAGBODY
            WALKER::RELIST-INTERNAL CAN-OPTIMIZE-ACCESS
            EMIT-GREATER-THAN-1-DLAP EMIT-1-T-DLAP EMIT-BOUNDP-CHECK
            WALKER::WALK-LABELS WALKER::WALK-SETQ
            WALKER::WALK-MULTIPLE-VALUE-SETQ WALKER::WALK-PROG
            SKIP-OPTIMIZE-SLOT-VALUE-BY-CLASS-P SKIP-FAST-SLOT-ACCESS-P
            FLUSH-CACHE-TRAP SORT-METHODS SORT-APPLICABLE-METHODS
            GET-NEW-FUNCTION-GENERATOR GET-FUNCTION-GENERATOR
            PRINT-STD-INSTANCE MAKE-TOP-LEVEL-FORM
            (SETF METHOD-FUNCTION-GET) WALKER::WALK-PROG*
            OBSOLETE-INSTANCE-TRAP
            ITERATE::SIMPLE-EXPAND-GATHERING-FORM
            ITERATE::VARIABLE-SAME-P WALKER::WALK-TAGBODY-1
            WALKER::WALK-UNEXPECTED-DECLARE OPTIMIZE-SLOT-BOUNDP
            OPTIMIZE-SET-SLOT-VALUE OPTIMIZE-SLOT-VALUE
            STANDARD-COMPUTE-EFFECTIVE-METHOD 
            EXPAND-DEFGENERIC WALKER::WALK-FLET WALKER::WALK-MACROLET
            WALKER::WALK-COMPILER-LET WALKER::WALK-SYMBOL-MACROLET
            WALKER::WALK-LOCALLY WALKER::WALK-LET* WALKER::WALK-LET
            NOTE-PV-TABLE-REFERENCE MAKE-METHOD-INITARGS-FORM-INTERNAL
            INITIALIZE-INTERNAL-SLOT-GFS* CONVERT-TABLE
            ITERATE::OPTIMIZE-GATHERING-FORM
            ITERATE::OPTIMIZE-ITERATE-FORM COMPUTE-PRECEDENCE
            FIRST-FORM-TO-LISP ONE-INDEX-DFUN-INFO ONE-CLASS-DFUN-INFO
            WRAP-METHOD-GROUP-SPECIFIER-BINDINGS MAP-ALL-ORDERS
            WALKER::WALK-IF WALKER::WITH-AUGMENTED-ENVIRONMENT-INTERNAL
            FIX-SLOT-ACCESSORS TRACE-METHOD-INTERNAL INVALIDATE-WRAPPER
            TRACE-EMF-CALL-INTERNAL MAKE-DFUN-CALL
            WALKER::WALK-NAMED-LAMBDA WALKER::WALK-LAMBDA
            WALKER::WALK-DO* WALKER::WALK-DO VARIABLE-DECLARATION
            WALKER::RECONS OPTIMIZE-GF-CALL-INTERNAL
            |(FAST-METHOD CLASS-DEFAULT-INITARGS (BUILT-IN-CLASS))|
            |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (BUILT-IN-CLASS))|
            |(FAST-METHOD CLASS-SLOTS (BUILT-IN-CLASS))|
            |(FAST-METHOD CLASS-DIRECT-SLOTS (BUILT-IN-CLASS))|
            |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
            CHANGE-CLASS-INTERNAL
            MAKE-OPTIMIZED-STD-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-METHOD-SPEC
            |(FAST-METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
            |(FAST-METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
            |(FAST-METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
            |(FAST-METHOD COMPUTE-SLOTS (STD-CLASS))|
            |(FAST-METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
            |(FAST-METHOD FINALIZE-INHERITANCE (STD-CLASS))|
            |(FAST-METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
            |(FAST-METHOD CLASS-PREDICATE-NAME (T))|
            |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (SPECIALIZER-WITH-OBJECT))|
            |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
            |(FAST-METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
            |(FAST-METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
            |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|
            |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
            |(FAST-METHOD CLASS-SLOT-CELLS (STD-CLASS))|
            |(FAST-METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
            |(FAST-METHOD CLASS-DEFAULT-INITARGS (SLOT-CLASS))|
            |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (SLOT-CLASS))|
            |(FAST-METHOD CLASS-FINALIZED-P (PCL-CLASS))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T)
            |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD FIND-METHOD (STANDARD-GENERIC-FUNCTION T T))|
            SET-ARG-INFO1 OPTIMIZE-GF-CALL
            BOOTSTRAP-MAKE-SLOT-DEFINITION
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT-1 LOAD-DEFCLASS
            REAL-LOAD-DEFCLASS EMIT-SLOT-ACCESS
            MAKE-EARLY-CLASS-DEFINITION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) PRECOMPUTE-EFFECTIVE-METHODS MAP-CACHE
            PROBE-CACHE CPL-ERROR REAL-ADD-METHOD
            MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE METHOD-FUNCTION-GET
            WALKER::CONVERT-MACRO-TO-LAMBDA GET-METHOD-FUNCTION-PV-CELL
            COMPUTE-SECONDARY-DISPATCH-FUNCTION1
            REAL-ENSURE-GF-USING-CLASS--NULL
            EXPAND-EFFECTIVE-METHOD-FUNCTION GET-DECLARATION
            RECORD-DEFINITION GET-EFFECTIVE-METHOD-FUNCTION1
            REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION
            (SETF FIND-CLASS) INITIALIZE-INFO MAKE-EMF-FROM-METHOD
            ENSURE-GENERIC-FUNCTION-USING-CLASS
            NAMED-OBJECT-PRINT-FUNCTION FIND-CLASS-PREDICATE-FROM-CELL
            FIND-CLASS-FROM-CELL EMIT-MISS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) T) FILL-CACHE REAL-GET-METHOD
            GET-METHOD WALKER::WALK-ARGLIST CAN-OPTIMIZE-ACCESS1
            CHECK-INITARGS-2-LIST CHECK-INITARGS-2-PLIST
            CHECK-INITARGS-1 MAKE-EMF-CALL EMIT-FETCH-WRAPPER)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T *) T) LOAD-DEFMETHOD
            MAKE-DEFMETHOD-FORM MAKE-DEFMETHOD-FORM-INTERNAL
            EARLY-MAKE-A-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) T) FILL-DFUN-CACHE
            REAL-ADD-NAMED-METHOD EARLY-ADD-NAMED-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T) T)
            GET-SECONDARY-DISPATCH-FUNCTION2)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T *) T)
            BOOTSTRAP-INITIALIZE-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T FIXNUM) T) FILL-CACHE-FROM-CACHE-P
            GET-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) T) EMIT-DLAP
            GET-SECONDARY-DISPATCH-FUNCTION1)) 
(PROCLAIM '(FTYPE (FUNCTION (T T FIXNUM) T) COMPUTE-STD-CPL-PHASE-3)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) T)
            |(FAST-METHOD SLOT-MISSING (T T T T))|
            LOAD-DEFMETHOD-INTERNAL EXPAND-DEFMETHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) EMIT-N-N-WRITERS EMIT-N-N-READERS
            COUNT-ALL-DFUNS)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) IN-THE-COMPILER-P RENEW-SYS-FILES
            INITIALIZE-CHECKING-OR-CACHING-FUNCTION-LIST MAKE-CACHE
            MAKE-ARG-INFO DISPATCH-DFUN-INFO MAKE-CPD
            STRUCTURE-FUNCTIONS-EXIST-P ALLOCATE-FUNCALLABLE-INSTANCE-1
            %%ALLOCATE-INSTANCE--CLASS SHOW-EMF-CALL-TRACE
            NO-METHODS-DFUN-INFO LIST-ALL-DFUNS
            ALLOCATE-FUNCALLABLE-INSTANCE-2 INITIAL-DISPATCH-DFUN-INFO
            INITIAL-DFUN-INFO DEFAULT-METHOD-ONLY-DFUN-INFO
            CACHES-TO-ALLOCATE BOOTSTRAP-META-BRAID
            UPDATE-DISPATCH-DFUNS GET-EFFECTIVE-METHOD-GENSYM
            BOOTSTRAP-BUILT-IN-CLASSES SHOW-DFUN-CONSTRUCTORS
            SHOW-FREE-CACHE-VECTORS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) *) UNTRACE-METHOD INVALID-METHOD-ERROR
            METHOD-COMBINATION-ERROR LIST-LARGE-CACHES
            UPDATE-MAKE-INSTANCE-FUNCTION-TABLE)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T *) *) FIND-FREE-CACHE-LINE)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T T) *) COMPUTE-CACHE-PARAMETERS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) PROTOTYPES-FOR-MAKE-METHOD-LAMBDA
            GENERIC-FUNCTION-NAME-P ANALYZE-LAMBDA-LIST *NORMALIZE-TYPE
            EMIT-IN-CHECKING-CACHE-P STRUCTURE-WRAPPER
            STRUCTURE-SLOTD-INIT-FORM MAKE-FINAL-DISPATCH-DFUN
            MAKE-DISPATCH-DFUN PARSE-METHOD-GROUP-SPECIFIER
            EARLY-COLLECT-INHERITANCE METHOD-PROTOTYPE-FOR-GF
            CLASS-EQ-TYPE FIND-WRAPPER EMIT-ONE-INDEX-WRITERS
            EMIT-ONE-INDEX-READERS FIND-STRUCTURE-CLASS
            COMPUTE-APPLICABLE-METHODS-EMF PCL-DESCRIBE
            GET-DISPATCH-FUNCTION TYPE-FROM-SPECIALIZER PARSE-DEFMETHOD
            GET-GENERIC-FUNCTION-INFO NET-CODE-CONVERTER
            DEFAULT-CODE-CONVERTER INSURE-CACHING-DFUN
            SPECIALIZER-FROM-TYPE
            EARLY-METHOD-STANDARD-ACCESSOR-SLOT-NAME
            COMPILE-IIS-FUNCTIONS CONVERT-TO-SYSTEM-TYPE
            EMIT-CONSTANT-VALUE EMIT-TWO-CLASS-WRITER
            EMIT-TWO-CLASS-READER EMIT-ONE-CLASS-WRITER
            EMIT-ONE-CLASS-READER EARLY-METHOD-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) STRING-APPEND FALSE MAKE-INITIALIZE-INFO
            PV-WRAPPERS-FROM-PV-ARGS MAKE-PV-TABLE
            |__si::MAKE-ONE-INDEX| MAKE-FAST-INSTANCE-BOUNDP TRUE ZERO
            |__si::MAKE-DEFAULT-METHOD-ONLY| |__si::MAKE-INITIAL|
            WALKER::UNBOUND-LEXICAL-FUNCTION |__si::MAKE-CACHING|
            |__si::MAKE-CHECKING| MAKE-PROGN |__si::MAKE-DISPATCH|
            |__si::MAKE-INITIAL-DISPATCH| |__si::MAKE-NO-METHODS|
            |__si::MAKE-CLASS-PRECEDENCE-DESCRIPTION|
            |STRUCTURE-OBJECT class constructor|
            FIX-EARLY-GENERIC-FUNCTIONS |__si::MAKE-N-N|
            |__si::MAKE-CACHE| INTERN-PV-TABLE USE-PACKAGE-PCL
            |__si::MAKE-ONE-INDEX-DFUN-INFO|
            |__si::MAKE-ACCESSOR-DFUN-INFO| |__si::MAKE-DFUN-INFO|
            |__si::MAKE-ARG-INFO| MAKE-FAST-METHOD-CALL
            MAKE-METHOD-CALL |__si::MAKE-PV-TABLE|
            |__si::MAKE-STD-INSTANCE| |__si::MAKE-CONSTANT-VALUE|
            |__si::MAKE-TWO-CLASS| |__si::MAKE-ONE-CLASS|
            CALLED-FIN-WITHOUT-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T FIXNUM *) T)
            COMPUTE-PRIMARY-CACHE-LOCATION-FROM-LOCATION
            GET-CACHE-FROM-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) DNET-METHODS-P DO-STANDARD-DEFSETF-1
            LEGAL-CLASS-NAME-P DEFAULT-STRUCTURE-TYPE
            DEFAULT-STRUCTURE-INSTANCE-P TWO-CLASS-P
            TWO-CLASS-ACCESSOR-TYPE ECD-METACLASS ECD-SOURCE
            INITIALIZE-INFO-P
            INITIALIZE-INFO-CACHED-MAKE-INSTANCE-FUNCTION-SYMBOL
            INITIALIZE-INFO-CACHED-COMBINED-INITARGS-FORM-LIST
            INITIALIZE-INFO-CACHED-INITARGS-FORM-LIST
            INITIALIZE-INFO-CACHED-RI-VALID-P
            INITIALIZE-INFO-CACHED-VALID-P
            GET-MAKE-INSTANCE-FUNCTION-SYMBOL
            GET-MAKE-INSTANCE-FUNCTIONS ONE-INDEX-P
            ONE-INDEX-ACCESSOR-TYPE ONE-CLASS-P ONE-CLASS-ACCESSOR-TYPE
            ONE-INDEX-DFUN-INFO-P ONE-INDEX-DFUN-INFO-ACCESSOR-TYPE
            INITIAL-DISPATCH-P INITIAL-P
            METHODS-CONTAIN-EQL-SPECIALIZER-P EVAL-FORM ARG-INFO-APPLYP
            INTERNED-SYMBOL-P ARG-INFO-KEYWORDS DEFAULT-METHOD-ONLY-P
            CACHING-CACHE GET-BUILT-IN-WRAPPER-SYMBOL
            GET-BUILT-IN-CLASS-SYMBOL EARLY-COLLECT-CPL SHOW-DFUN-COSTS
            METHOD-FUNCTION-PLIST METHOD-CALL-P EXPAND-LONG-DEFCOMBIN
            EXPAND-SHORT-DEFCOMBIN CPD-SUPERS WALKER::ENV-LOCK
            SYMBOL-PKG-NAME STRUCTURE-SLOT-BOUNDP
            COMPUTE-MCASE-PARAMETERS FUNCTION-RETURNING-T
            FGEN-GENERATOR COMPLICATED-INSTANCE-CREATION-METHOD
            TWO-CLASS-INDEX INITIALIZE-INFO-CACHED-NEW-KEYS
            RESET-CLASS-INITIALIZE-INFO-1 UNDEFMETHOD-1 ONE-INDEX-INDEX
            ONE-CLASS-INDEX ONE-INDEX-DFUN-INFO-INDEX LIST-LARGE-CACHE
            GBOUNDP WRAPPER-FIELD FREE-CACHE CHECKING-FUNCTION
            EXTRACT-REQUIRED-PARAMETERS EXTRACT-PARAMETERS
            METHOD-CALL-CALL-METHOD-ARGS CACHING-DFUN-INFO
            EARLY-CLASS-NAME-OF FAST-METHOD-CALL-ARG-INFO
            DISPATCH-CACHE
            WALKER::GET-IMPLEMENTATION-DEPENDENT-WALKER-TEMPLATE
            WALKER::GET-WALKER-TEMPLATE SORT-SLOTS COMPUTE-CLASS-SLOTS
            CLASS-HAS-A-FORWARD-REFERENCED-SUPERCLASS-P
            SLOT-BOUNDP-SYMBOL SLOT-WRITER-SYMBOL SLOT-READER-SYMBOL
            CLASS-FROM-TYPE FUNCTION-PRETTY-ARGLIST
            FGEN-GENERATOR-LAMBDA FGEN-GENSYMS ACCESSOR-DFUN-INFO-P
            ECD-SUPERCLASS-NAMES COMPUTE-STD-CPL-PHASE-2
            FUNCALLABLE-INSTANCE-P WRAPPER-OF UNPARSE-SPECIALIZERS
            MAKE-INITIAL-DFUN N-N-CACHE CACHE-OWNER STORE-FGEN
            SLOT-VECTOR-SYMBOL SLOT-INITARGS-FROM-STRUCTURE-SLOTD
            METHOD-FUNCTION-METHOD EARLY-METHOD-CLASS CHECKING-CACHE
            CLASS-PRECEDENCE-DESCRIPTION-P CHECK-CACHE
            ACCESSOR-DFUN-INFO-ACCESSOR-TYPE %STD-INSTANCE-WRAPPER
            METHOD-LL->GENERIC-FUNCTION-LL GET-SETF-FUNCTION-NAME
            INTERN-FUNCTION-NAME DEFAULT-STRUCTUREP
            STRUCTURE-SLOTD-TYPE STD-INSTANCE-P
            ITERATE::SEQUENCE-ACCESSOR MAKE-FUNCTION-INLINE
            STRUCTURE-SLOTD-ACCESSOR-SYMBOL
            STRUCTURE-TYPE-SLOT-DESCRIPTION-LIST STRUCTURE-TYPE-P
            STRUCTURE-TYPE ECD-OTHER-INITARGS
            INITIALIZE-INFO-BOUND-SLOTS
            INITIALIZE-INFO-CACHED-CONSTANTS INITIALIZE-INFO-KEY
            LIST-DFUN ARG-INFO-PRECEDENCE STRUCTURE-OBJECT-P
            GET-CACHE-VECTOR KEYWORD-SPEC-NAME
            FTYPE-DECLARATION-FROM-LAMBDA-LIST CHECK-WRAPPER-VALIDITY
            WALKER::ENV-WALK-FUNCTION VARIABLE-GLOBALLY-SPECIAL-P
            PV-TABLEP METHOD-FUNCTION-FROM-FAST-FUNCTION
            UPDATE-PV-TABLE-CACHE-INFO MAP-ALL-GENERIC-FUNCTIONS
            DEFAULT-SECONDARY-DISPATCH-FUNCTION UPDATE-C-A-M-GF-INFO
            UPDATE-GF-INFO UPDATE-ALL-C-A-M-GF-INFO FGEN-SYSTEM
            USE-CACHING-DFUN-P USE-DEFAULT-METHOD-ONLY-DFUN-P
            TWO-CLASS-WRAPPER0 NO-METHODS-CACHE CONSTANT-VALUE-CACHE
            COMPUTE-LINE-SIZE COPY-CACHE
            INITIALIZE-INFO-CACHED-MAKE-INSTANCE-FUNCTION
            INITIALIZE-INFO-CACHED-COMBINED-INITIALIZE-FUNCTION
            INITIALIZE-INFO-CACHED-SHARED-INITIALIZE-NIL-FUNCTION
            INITIALIZE-INFO-CACHED-SHARED-INITIALIZE-T-FUNCTION
            INITIALIZE-INFO-CACHED-DEFAULT-INITARGS-FUNCTION
            MAKE-INSTANCE-FUNCTION-SYMBOL GET-MAKE-INSTANCE-FUNCTION
            ONE-CLASS-WRAPPER0 DFUN-INFO-CACHE
            UNENCAPSULATED-FDEFINITION GF-DFUN-CACHE
            GF-INFO-STATIC-C-A-M-EMF CLASS-PREDICATE
            FLUSH-CACHE-VECTOR-INTERNAL CACHING-DFUN-COST CACHING-P
            EARLY-CLASS-DIRECT-SUBCLASSES EARLY-CLASS-PRECEDENCE-LIST
            CACHE-P EARLY-METHOD-LAMBDA-LIST
            EARLY-METHOD-STANDARD-ACCESSOR-P GENERIC-CLOBBERS-FUNCTION
            FAST-INSTANCE-BOUNDP-P FAST-METHOD-CALL-P EARLY-GF-P
            UPDATE-GFS-OF-CLASS PROCLAIM-INCOMPATIBLE-SUPERCLASSES
            STRUCTURE-SVUC-METHOD STANDARD-SVUC-METHOD
            COMPILE-LAMBDA-DEFERRED COMPILE-LAMBDA-UNCOMPILED CCLOSUREP
            TWO-CLASS-CACHE CONSTANT-VALUE-DFUN-INFO
            ECD-CANONICAL-SLOTS ECD-CLASS-NAME ONE-INDEX-CACHE
            ONE-CLASS-CACHE ONE-INDEX-DFUN-INFO-CACHE
            INITIAL-DISPATCH-CACHE INITIAL-CACHE GF-DFUN-INFO
            ARG-INFO-VALID-P ARG-INFO-P ARG-INFO-KEY/REST-P
            ARG-INFO-METATYPES ARG-INFO-LAMBDA-LIST
            FINAL-ACCESSOR-DFUN-TYPE DEFAULT-METHOD-ONLY-CACHE
            DISPATCH-P TYPE-CLASS EARLY-COLLECT-DEFAULT-INITARGS
            FIND-CYCLE-REASONS NEXT-WRAPPER-FIELD GDEFINITION CPD-AFTER
            CPD-CLASS ALLOCATE-CACHE-VECTOR
            SYSTEM:%COMPILED-FUNCTION-NAME MAP-SPECIALIZERS
            DO-STANDARD-DEFSETFS-FOR-DEFCLASS
            ITERATE::VARIABLES-FROM-LET STRUCTURE-SLOTD-NAME
            STRUCTURE-TYPE-INCLUDED-TYPE-NAME COUNT-DFUN
            TWO-CLASS-WRAPPER1 DEFAULT-CONSTANTP
            RESET-CLASS-INITIALIZE-INFO RESET-INITIALIZE-INFO
            WRAPPER-FOR-STRUCTURE ARG-INFO-NKEYS N-N-P
            N-N-ACCESSOR-TYPE MAKE-EQL-PREDICATE
            MAKE-CLASS-EQ-PREDICATE MAKE-TYPE-PREDICATE
            PARSE-SPECIALIZERS EARLY-METHOD-QUALIFIERS CHECKING-P
            %FBOUNDP SORT-CALLS MAKE-PERMUTATION-VECTOR
            UPDATE-CLASS-CAN-PRECEDE-P NET-TEST-CONVERTER
            UPDATE-GF-SIMPLE-ACCESSOR-TYPE SETFBOUNDP
            STRUCTURE-SLOTD-WRITER-FUNCTION
            STRUCTURE-SLOTD-READER-FUNCTION
            STRUCTURE-TYPE-INTERNAL-SLOTDS LOOKUP-FGEN FGEN-TEST
            DEFAULT-CONSTANT-CONVERTER DEFAULT-TEST-CONVERTER
            INITIALIZE-INFO-WRAPPER GET-PV-CELL-FOR-CLASS
            INTERN-EQL-SPECIALIZER INFORM-TYPE-SYSTEM-ABOUT-STD-CLASS
            EXPAND-MAKE-INSTANCE-FORM GMAKUNBOUND
            EARLY-ACCESSOR-METHOD-SLOT-NAME EARLY-SLOT-DEFINITION-NAME
            EARLY-CLASS-NAME EARLY-COLLECT-SLOTS EARLY-CLASS-SLOTS
            METHOD-FUNCTION-PV-TABLE CANONICAL-SLOT-NAME
            FAST-METHOD-CALL-NEXT-METHOD-CALL FAST-METHOD-CALL-PV-CELL
            EARLY-GF-NAME ACCESSOR-DFUN-INFO-CACHE
            ARG-INFO-NUMBER-OPTIONAL %STD-INSTANCE-SLOTS
            SYSTEM:%STRUCTURE-NAME WALKER::ENV-LEXICAL-VARIABLES
            WALKER::ENV-DECLARATIONS WALKER::ENV-WALK-FORM
            MAKE-CALLS-TYPE-DECLARATION MAKE-PV-TYPE-DECLARATION
            MAKE-PV-TABLE-TYPE-DECLARATION FORCE-CACHE-FLUSHES
            MAKE-OPTIMIZED-STRUCTURE-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            MAKE-OPTIMIZED-STRUCTURE-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-OPTIMIZED-STRUCTURE-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            MAKE-STRUCTURE-SLOT-BOUNDP-FUNCTION
            COMPUTE-APPLICABLE-METHODS-EMF-STD-P MAKE-CONSTANT-FUNCTION
            FUNCTION-RETURNING-NIL SFUN-P CONSTANT-SYMBOL-P
            NO-METHODS-P CONSTANT-VALUE-P FORMAT-CYCLE-REASONS
            BOOTSTRAP-CLASS-PREDICATES BOOTSTRAP-ACCESSOR-DEFINITIONS
            GFS-OF-TYPE DFUN-INFO-P FREE-CACHE-VECTOR DFUN-ARG-SYMBOL
            GF-LAMBDA-LIST GF-INFO-FAST-MF-P GF-INFO-C-A-M-EMF-STD-P
            GF-PRECOMPUTE-DFUN-AND-EMF-P GF-INFO-SIMPLE-ACCESSOR-TYPE
            MAKE-DEFAULT-METHOD-GROUP-DESCRIPTION
            EARLY-SLOT-DEFINITION-LOCATION EARLY-CLASS-SLOTDS
            MAKE-INITFUNCTION EARLY-CLASS-DEFINITION MAKE-CALL-METHODS
            EXTRACT-SPECIALIZER-NAMES EXTRACT-LAMBDA-LIST
            BUILT-IN-WRAPPER-OF CLASS-OF BUILT-IN-OR-STRUCTURE-WRAPPER1
            %CCLOSURE-ENV %SYMBOL-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) MAKE-CONSTANT-VALUE-DFUN
            MAKE-CACHING-DFUN WALK-FORM COMPILE-LAMBDA
            GET-DFUN-CONSTRUCTOR GET-FUNCTION1 GET-FUNCTION
            MAP-ALL-CLASSES ENSURE-GENERIC-FUNCTION GET-METHOD-FUNCTION
            PARSE-SPECIALIZED-LAMBDA-LIST MAKE-INSTANCE-1
            DISPATCH-DFUN-COST COERCE-TO-CLASS MAKE-FINAL-DFUN-INTERNAL
            MAKE-METHOD-LAMBDA-INTERNAL MAKE-METHOD-FUNCTION-INTERNAL
            CALL-NO-NEXT-METHOD MACROEXPAND-ALL ENSURE-CLASS
            EXTRACT-DECLARATIONS PARSE-METHOD-OR-SPEC)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) (VALUES T T)) SYMBOL-APPEND)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) SLOT-BOUNDP SLOT-VALUE FORM-LIST-TO-LISP
            COMPUTE-STD-CPL-PHASE-1 SAUT-CLASS-EQ
            MUTATE-SLOTS-AND-CALLS DESTRUCTURE SAUT-AND COMPUTE-CODE
            GET-NEW-FUNCTION-GENERATOR-INTERNAL SAUT-CLASS SAUT-NOT
            CLASS-APPLICABLE-USING-CLASS-P SET-FUNCTION-NAME
            EMIT-DEFAULT-ONLY MAKE-DIRECT-SLOTD SLOT-UNBOUND-INTERNAL
            UPDATE-SLOT-VALUE-GF-INFO SDFUN-FOR-CACHING
            ITERATE::PARSE-DECLARATIONS EMIT-CACHING EMIT-CHECKING
            SAUT-PROTOTYPE SLOT-NAME-LISTS-FROM-SLOTS
            MAKE-INSTANCE-FUNCTION-TRAP EMIT-DEFAULT-ONLY-FUNCTION
            SAUT-EQL INVOKE-EMF CHECK-INITARGS-VALUES
            FIND-SUPERCLASS-CHAIN SPLIT-DECLARATIONS INITIAL-DFUN
            SPECIALIZER-APPLICABLE-USING-TYPE-P *SUBTYPEP
            GENERATE-FAST-CLASS-SLOT-ACCESS-P SLOT-MAKUNBOUND
            COMPUTE-TEST COMPUTE-APPLICABLE-METHODS-USING-TYPES
            ENSURE-CLASS-VALUES)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) ALLOCATE-STRUCTURE-INSTANCE
            ALLOCATE-FUNCALLABLE-INSTANCE ALLOCATE-STANDARD-INSTANCE
            WALKER::RELIST* PV-TABLE-LOOKUP-PV-ARGS MAKE-SPECIALIZABLE
            ITERATE::FUNCTION-LAMBDA-P MAKE-FINAL-DFUN MAKE-WRAPPER
            FIND-CLASS USE-DISPATCH-DFUN-P USE-CONSTANT-VALUE-DFUN-P
            INITIALIZE-METHOD-FUNCTION
            WALKER::WALKER-ENVIRONMENT-BIND-1
            INITIALIZE-INTERNAL-SLOT-GFS ITERATE::MAYBE-WARN
            UPDATE-DFUN MAKE-EARLY-GF SET-ARG-INFO
            EARLY-METHOD-SPECIALIZERS FIND-CLASS-PREDICATE TRACE-METHOD
            MAKE-TYPE-PREDICATE-NAME SET-DFUN WALKER::RELIST
            FIND-CLASS-CELL CAPITALIZE-WORDS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) REMOVE-DIRECT-SUBCLASSES
            (SETF FIND-CLASS-PREDICATE)
            FUNCALLABLE-STANDARD-INSTANCE-ACCESS FIND-SLOT-DEFINITION
            MAKE-UNORDERED-METHODS-EMF MEC-ALL-CLASSES
            SET-FUNCTION-PRETTY-ARGLIST ITERATE::MV-SETQ
            ITERATE::EXTRACT-SPECIAL-BINDINGS BOOTSTRAP-SLOT-INDEX
            DESCRIBE-PACKAGE SAUT-NOT-CLASS-EQ
            UPDATE-INITIALIZE-INFO-INTERNAL PLIST-VALUE
            MAP-PV-TABLE-REFERENCES-OF UPDATE-INITS UPDATE-SLOTS
            ADD-DIRECT-SUBCLASSES STANDARD-INSTANCE-ACCESS LIST-EQ
            CPL-INCONSISTENT-ERROR CPL-FORWARD-REFERENCED-CLASS-ERROR
            %SET-CCLOSURE-ENV (SETF METHOD-FUNCTION-PLIST)
            WALKER::NOTE-LEXICAL-BINDING PV-WRAPPERS-FROM-ALL-ARGS
            REMOVE-SLOT-ACCESSORS CLASS-CAN-PRECEDE-P SLOT-EXISTS-P
            SET-STRUCTURE-SVUC-METHOD SET-STANDARD-SVUC-METHOD
            SUPERCLASSES-COMPATIBLE-P REAL-REMOVE-METHOD
            MEC-ALL-CLASSES-INTERNAL AUGMENT-TYPE
            UPDATE-STD-OR-STR-METHODS DESTRUCTURE-INTERNAL
            COMPUTE-CONSTANTS EMIT-1-NIL-DLAP PROCLAIM-DEFGENERIC
            SAUT-NOT-CLASS VARIABLE-CLASS REMOVE-METHOD
            REDIRECT-EARLY-FUNCTION-INTERNAL
            CLASSES-HAVE-COMMON-SUBCLASS-P CLASS-MIGHT-PRECEDE-P
            WALKER::NOTE-DECLARATION WALKER::ENVIRONMENT-MACRO
            PV-WRAPPERS-FROM-ALL-WRAPPERS PV-TABLE-LOOKUP UPDATE-CPL
            ADD-SLOT-ACCESSORS SWAP-WRAPPERS-AND-SLOTS
            COMPUTE-APPLICABLE-METHODS-FUNCTION MEC-ALL-CLASS-LISTS
            N-N-DFUN-INFO CHECKING-DFUN-INFO FDEFINE-CAREFULLY
            ADD-METHOD WALKER::ENVIRONMENT-FUNCTION VARIABLE-SPECIAL-P
            WALKER::VARIABLE-SYMBOL-MACRO-P VARIABLE-LEXICAL-P
            SET-METHODS MAKE-DISCRIMINATING-FUNCTION-ARGLIST
            REDEFINE-FUNCTION MAKE-PLIST
            ITERATE::SIMPLE-EXPAND-ITERATE-FORM COMPUTE-STD-CPL
            SET-FUNCALLABLE-INSTANCE-FUNCTION SAUT-NOT-PROTOTYPE
            DEAL-WITH-ARGUMENTS-OPTION
            MAKE-FAST-METHOD-CALL-LAMBDA-LIST RAISE-METATYPE
            MAKE-DFUN-ARG-LIST MAKE-DLAP-LAMBDA-LIST
            MAKE-DFUN-LAMBDA-LIST ADD-TO-CVECTOR UPDATE-CLASS
            EMIT-N-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            EMIT-1-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION SAUT-NOT-EQL
            QUALIFIER-CHECK-RUNTIME PARSE-QUALIFIER-PATTERN ADD-FORMS
            WALKER::WALK-REPEAT-EVAL COMPUTE-PV MAKE-PV-TABLE-INTERNAL
            NO-SLOT REMTAIL DOCTOR-DFUN-FOR-THE-DEBUGGER
            ACCESSOR-MISS-FUNCTION MAKE-CLASS-PREDICATE
            METHOD-FUNCTION-RETURNING-NIL GET-KEY-ARG-TAIL
            (SETF GDEFINITION) COMPUTE-CALLS UPDATE-ALL-PV-TABLE-CACHES
            SET-WRAPPER METHODS-CONVERTER NET-CONSTANT-CONVERTER
            VALUE-FOR-CACHING MAKE-CDXR MAKE-CAXR PROCLAIM-DEFMETHOD
            PRINTING-RANDOM-THING-INTERNAL FIND-STANDARD-II-METHOD
            MAKE-EARLY-ACCESSOR MEMF-CONSTANT-CONVERTER
            SYSTEM:%SET-COMPILED-FUNCTION-NAME SYMBOL-OR-CONS-LESSP
            SYMBOL-LESSP COMPUTE-LAYOUT MAKE-STD-BOUNDP-METHOD-FUNCTION
            MAKE-STD-WRITER-METHOD-FUNCTION
            MAKE-STD-READER-METHOD-FUNCTION
            MAKE-INTERNAL-READER-METHOD-FUNCTION DO-SATISFIES-DEFTYPE
            CANONICALIZE-DEFCLASS-OPTION
            CANONICALIZE-SLOT-SPECIFICATION
            METHOD-FUNCTION-RETURNING-T)) 
(PROCLAIM '(FTYPE (FUNCTION NIL FIXNUM) GET-WRAPPER-CACHE-NUMBER)) 
(IN-PACKAGE "PCL")

(DOLIST (V '(|(FAST-WRITER-METHOD SLOT-OBJECT FROM-DEFCLASS-P)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-METHODS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SLOTS)|
                |(FAST-WRITER-METHOD SLOT-CLASS SLOTS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-SLOTS)|
                |(FAST-WRITER-METHOD SLOT-CLASS DIRECT-SLOTS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHODS)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION METHODS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT OPTIONS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-SUBCLASSES)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-SUPERCLASSES)|
                ADD-READER-METHOD
                SHORT-COMBINATION-IDENTITY-WITH-ONE-ARGUMENT
                REMOVE-READER-METHOD |LISP::T class predicate|
                EQL-SPECIALIZER-P |(SETF GENERIC-FUNCTION-NAME)|
                OBJECT-PLIST SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL
                |PCL::STANDARD-OBJECT class predicate|
                |PCL::STANDARD-SLOT-DEFINITION class predicate|
                |PCL::STANDARD-DIRECT-SLOT-DEFINITION class predicate|
                |PCL::STANDARD-EFFECTIVE-SLOT-DEFINITION class predicate|
                |PCL::STANDARD-METHOD-COMBINATION class predicate|
                |(FAST-READER-METHOD SLOT-OBJECT METHOD)|
                |PCL::BUILT-IN-CLASS class predicate| SPECIALIZER-TYPE
                |LISP::RATIO class predicate|
                |LISP::RATIONAL class predicate| GF-DFUN-STATE
                |(SETF GENERIC-FUNCTION-METHOD-CLASS)|
                |(FAST-READER-METHOD SLOT-OBJECT DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(FAST-READER-METHOD STRUCTURE-SLOT-DEFINITION DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(SETF GENERIC-FUNCTION-METHOD-COMBINATION)|
                CLASS-DEFSTRUCT-CONSTRUCTOR
                |(FAST-READER-METHOD SLOT-OBJECT SOURCE)|
                |(FAST-READER-METHOD DEFINITION-SOURCE-MIXIN SOURCE)|
                METHOD-FAST-FUNCTION |(SETF GENERIC-FUNCTION-METHODS)|
                |(SETF GENERIC-FUNCTION-DECLARATIONS)|
                |(SETF GF-PRETTY-ARGLIST)|
                |(FAST-READER-METHOD SLOT-OBJECT INITIALIZE-INFO)|
                |(FAST-READER-METHOD SLOT-CLASS INITIALIZE-INFO)|
                |(FAST-READER-METHOD SLOT-OBJECT ARG-INFO)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION ARG-INFO)|
                SPECIALIZERP EXACT-CLASS-SPECIALIZER-P
                |(FAST-READER-METHOD SLOT-OBJECT WRAPPER)|
                |(FAST-READER-METHOD PCL-CLASS WRAPPER)|
                |(FAST-READER-METHOD SLOT-OBJECT INITARGS)|
                |(FAST-READER-METHOD SLOT-DEFINITION INITARGS)|
                |(FAST-READER-METHOD SHORT-METHOD-COMBINATION OPERATOR)|
                |(FAST-READER-METHOD SLOT-OBJECT OPERATOR)|
                |(FAST-READER-METHOD SLOT-OBJECT DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-READER-METHOD STRUCTURE-CLASS DEFSTRUCT-CONSTRUCTOR)|
                COMPATIBLE-META-CLASS-CHANGE-P
                |LISP::CHARACTER class predicate|
                |LISP::SEQUENCE class predicate|
                |(FAST-READER-METHOD SLOT-OBJECT CLASS-EQ-SPECIALIZER)|
                |(FAST-READER-METHOD CLASS CLASS-EQ-SPECIALIZER)|
                |(BOUNDP READER-FUNCTION)| |(BOUNDP PREDICATE-NAME)|
                |(BOUNDP READERS)| UPDATE-GF-DFUN
                |(BOUNDP CLASS-PRECEDENCE-LIST)|
                |(BOUNDP ACCESSOR-FLAGS)| |(BOUNDP LOCATION)|
                |(BOUNDP DOCUMENTATION)| SPECIALIZER-OBJECT
                |(BOUNDP INCOMPATIBLE-SUPERCLASS-LIST)|
                LONG-METHOD-COMBINATION-P ACCESSOR-METHOD-SLOT-NAME
                |(BOUNDP SPECIALIZERS)|
                |(BOUNDP IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DEFSTRUCT-ACCESSOR-SYMBOL)|
                SPECIALIZER-CLASS |(BOUNDP PRETTY-ARGLIST)|
                |PCL::PCL-CLASS class predicate|
                |PCL::STD-CLASS class predicate|
                |(BOUNDP DEFSTRUCT-FORM)|
                |(SETF SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL)|
                CLASS-EQ-SPECIALIZER-P
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SOURCE)| SLOTS-FETCHER
                |(BOUNDP ARGUMENTS-LAMBDA-LIST)|
                |(SETF SLOT-ACCESSOR-STD-P)| REMOVE-WRITER-METHOD
                |(BOUNDP WRITER-FUNCTION)| |(BOUNDP INITFUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITIALIZE-INFO)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ARG-INFO)|
                STRUCTURE-CLASS-P |(BOUNDP WRITERS)|
                |(BOUNDP INITFORM)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT WRAPPER)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITARGS)|
                |LISP::BIT-VECTOR class predicate|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DEFSTRUCT-CONSTRUCTOR)|
                UPDATE-CONSTRUCTORS |(BOUNDP SLOT-NAME)|
                |(SETF SLOT-DEFINITION-INITARGS)| |(BOUNDP ALLOCATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CLASS-EQ-SPECIALIZER)|
                DOCUMENTATION |(BOUNDP FUNCTION)|
                |(BOUNDP GENERIC-FUNCTION)| |(BOUNDP LAMBDA-LIST)|
                METHOD-PRETTY-ARGLIST |(BOUNDP SLOT-DEFINITION)|
                |LISP::ARRAY class predicate|
                |(BOUNDP CAN-PRECEDE-LIST)| |(BOUNDP PROTOTYPE)|
                CLASS-EQ-SPECIALIZER INFORM-TYPE-SYSTEM-ABOUT-CLASS
                |PCL::DEFINITION-SOURCE-MIXIN class predicate|
                |(BOUNDP DFUN-STATE)|
                |LISP::STRUCTURE-OBJECT class predicate|
                |(BOUNDP FROM-DEFCLASS-P)| |(READER METHOD)|
                |LISP::STANDARD-OBJECT class predicate|
                |(CALL STANDARD-COMPUTE-EFFECTIVE-METHOD)|
                |(BOUNDP FAST-FUNCTION)|
                |LISP::COMPLEX class predicate| |(BOUNDP METHOD-CLASS)|
                |(READER SOURCE)| |(BOUNDP INTERNAL-WRITER-FUNCTION)|
                |(BOUNDP INTERNAL-READER-FUNCTION)|
                |(BOUNDP METHOD-COMBINATION)| ACCESSOR-METHOD-CLASS
                |(BOUNDP DIRECT-SLOTS)| |(BOUNDP DIRECT-METHODS)|
                |(BOUNDP BOUNDP-FUNCTION)| |(BOUNDP DIRECT-SUBCLASSES)|
                |(BOUNDP DIRECT-SUPERCLASSES)| |(BOUNDP METHODS)|
                |(BOUNDP OPTIONS)| |(WRITER METHOD)|
                |LISP::BUILT-IN-CLASS class predicate|
                |PCL::DEPENDENT-UPDATE-MIXIN class predicate|
                GENERIC-FUNCTION-PRETTY-ARGLIST |(WRITER SOURCE)|
                |(FAST-METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (STANDARD-OBJECT STANDARD-OBJECT))|
                |(FAST-METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(FAST-METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
                |(FAST-METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
                |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (SPECIALIZER-WITH-OBJECT))|
                |(FAST-METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
                |(FAST-METHOD SAME-SPECIALIZER-P (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
                |(FAST-METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
                |(FAST-METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
                |(FAST-METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
                |(FAST-METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
                MAKE-BOUNDP-METHOD-FUNCTION
                |LISP::STRING class predicate|
                |(FAST-METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
                |(FAST-METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
                |PCL::METAOBJECT class predicate|
                |(FAST-METHOD CHANGE-CLASS (T SYMBOL))|
                |(FAST-METHOD (SETF DOCUMENTATION) (T STANDARD-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-VALUE-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-VALUE-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|
                |(FAST-METHOD METHOD-FUNCTION (STANDARD-METHOD))|
                |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
                |(FAST-METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
                |(FAST-METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
                |(FAST-METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
                |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
                |(FAST-METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
                |(FAST-METHOD MAKE-INSTANCE (SYMBOL))|
                |(FAST-METHOD DOCUMENTATION (STANDARD-SLOT-DEFINITION))|
                |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
                |(FAST-METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
                |(FAST-METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
                |(FAST-METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(FAST-METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(FAST-METHOD GENERIC-FUNCTION-PRETTY-ARGLIST (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS (EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
                |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-ACCESSOR-METHOD))|
                |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-WRITER-METHOD))|
                |(FAST-METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
                |(FAST-METHOD GENERIC-FUNCTION-LAMBDA-LIST (GENERIC-FUNCTION))|
                |(FAST-METHOD GF-FAST-METHOD-FUNCTION-P (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
                |(FAST-METHOD CLASS-PROTOTYPE (STD-CLASS))|
                |(FAST-METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
                |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (SLOT-CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
                |(FAST-METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
                |(FAST-METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD MAKE-INSTANCE (CLASS))|
                |(FAST-METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
                |(FAST-METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
                |(FAST-METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
                |(FAST-METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|
                |(FAST-METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
                |(FAST-METHOD CLASS-SLOT-CELLS (STD-CLASS))|
                |(FAST-METHOD SPECIALIZER-CLASS (CLASS))|
                |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
                |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|
                |(FAST-METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
                |(FAST-METHOD FINALIZE-INHERITANCE (STD-CLASS))|
                |(FAST-METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
                |(FAST-METHOD CLASS-FINALIZED-P (PCL-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS (STD-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
                |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (SLOT-CLASS))|
                |(FAST-METHOD CLASS-DEFAULT-INITARGS (SLOT-CLASS))|
                |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
                |(FAST-METHOD CLASS-DIRECT-SLOTS (BUILT-IN-CLASS))|
                |(FAST-METHOD CLASS-SLOTS (BUILT-IN-CLASS))|
                |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (BUILT-IN-CLASS))|
                |(FAST-METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
                |(FAST-METHOD CLASS-DEFAULT-INITARGS (BUILT-IN-CLASS))|
                |(FAST-METHOD SLOTS-FETCHER (STANDARD-CLASS))|
                |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
                |(FAST-METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
                |(FAST-METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
                |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
                CLASS-PREDICATE-NAME
                |PCL::STRUCTURE-OBJECT class predicate|
                |PCL::STRUCTURE-SLOT-DEFINITION class predicate|
                |PCL::STRUCTURE-DIRECT-SLOT-DEFINITION class predicate|
                |PCL::STRUCTURE-EFFECTIVE-SLOT-DEFINITION class predicate|
                |LISP::SYMBOL class predicate| CLASSP
                |PCL::EFFECTIVE-SLOT-DEFINITION class predicate|
                |(COMBINED-METHOD SHARED-INITIALIZE)|
                LEGAL-QUALIFIERS-P ADD-BOUNDP-METHOD
                LEGAL-LAMBDA-LIST-P |LISP::VECTOR class predicate|
                |SETF PCL GENERIC-FUNCTION-NAME|
                |(READER READER-FUNCTION)| |(READER PREDICATE-NAME)|
                |(READER READERS)| DESCRIBE-OBJECT
                |(READER CLASS-PRECEDENCE-LIST)|
                |(READER ACCESSOR-FLAGS)| |(READER LOCATION)|
                |(READER DOCUMENTATION)| CLASS-INITIALIZE-INFO
                |(SETF CLASS-SLOT-VALUE)| MAKE-WRITER-METHOD-FUNCTION
                |SETF PCL GF-DFUN-STATE|
                |(READER INCOMPATIBLE-SUPERCLASS-LIST)|
                |(READER SPECIALIZERS)|
                |(READER IDENTITY-WITH-ONE-ARGUMENT)|
                |(SETF CLASS-INITIALIZE-INFO)|
                |(READER PRETTY-ARGLIST)| |(READER DEFSTRUCT-FORM)|
                |SETF PCL SLOT-DEFINITION-NAME| |SETF PCL CLASS-NAME|
                |(WRITER READER-FUNCTION)|
                |(SETF CLASS-DEFSTRUCT-CONSTRUCTOR)|
                |(WRITER PREDICATE-NAME)|
                |(READER ARGUMENTS-LAMBDA-LIST)| |(WRITER READERS)|
                |(READER WRITER-FUNCTION)| |(READER INITFUNCTION)|
                INITIALIZE-INTERNAL-SLOT-FUNCTIONS
                |SETF PCL SLOT-DEFINITION-TYPE| |(READER WRITERS)|
                |(WRITER CLASS-PRECEDENCE-LIST)|
                |(WRITER ACCESSOR-FLAGS)| |(READER INITFORM)|
                METHOD-COMBINATION-P |(WRITER LOCATION)|
                |(WRITER DOCUMENTATION)|
                |(CALL REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION)|
                |SETF PCL GENERIC-FUNCTION-METHODS|
                |SETF PCL GENERIC-FUNCTION-METHOD-COMBINATION|
                |SETF PCL METHOD-GENERIC-FUNCTION| |(READER SLOT-NAME)|
                |(WRITER INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL SLOT-ACCESSOR-STD-P|
                |(CALL REAL-MAKE-METHOD-INITARGS-FORM)|
                |(READER ALLOCATION)| |(WRITER SPECIALIZERS)|
                |(CALL REAL-ENSURE-GF-USING-CLASS--NULL)|
                |(WRITER IDENTITY-WITH-ONE-ARGUMENT)|
                |(SETF METHOD-GENERIC-FUNCTION)|
                |(WRITER PRETTY-ARGLIST)| LEGAL-SPECIALIZERS-P
                |SETF PCL OBJECT-PLIST| |LISP::FLOAT class predicate|
                |(WRITER DEFSTRUCT-FORM)| |(READER FUNCTION)|
                |(READER GENERIC-FUNCTION)| |(READER LAMBDA-LIST)|
                |(READER SLOT-DEFINITION)|
                |PCL::CLASS-PROTOTYPE-SPECIALIZER class predicate|
                |SETF PCL SLOT-DEFINITION-INITFORM|
                |SETF PCL CLASS-DEFSTRUCT-FORM|
                |(WRITER ARGUMENTS-LAMBDA-LIST)|
                |(READER CAN-PRECEDE-LIST)|
                |SETF PCL GENERIC-FUNCTION-METHOD-CLASS|
                |(READER PROTOTYPE)| |(WRITER WRITER-FUNCTION)|
                |(WRITER INITFUNCTION)| |(WRITER WRITERS)|
                SLOT-ACCESSOR-STD-P |(WRITER INITFORM)|
                |(READER DFUN-STATE)| |(READER FROM-DEFCLASS-P)|
                |SETF PCL GF-PRETTY-ARGLIST|
                |SETF PCL SLOT-ACCESSOR-FUNCTION|
                |SETF PCL SLOT-DEFINITION-LOCATION|
                |SETF PCL SLOT-DEFINITION-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-BOUNDP-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-ALLOCATION|
                |SETF PCL SLOT-DEFINITION-INITFUNCTION|
                |(WRITER SLOT-NAME)| |(BOUNDP NAME)|
                |(READER FAST-FUNCTION)| |(WRITER ALLOCATION)|
                |(READER METHOD-CLASS)| |(SETF OBJECT-PLIST)|
                |(READER INTERNAL-WRITER-FUNCTION)|
                |(READER INTERNAL-READER-FUNCTION)|
                |(READER METHOD-COMBINATION)|
                METHOD-COMBINATION-OPTIONS |(READER DIRECT-SLOTS)|
                |(READER DIRECT-METHODS)|
                |SETF PCL SLOT-DEFINITION-READERS| |(WRITER FUNCTION)|
                |(WRITER GENERIC-FUNCTION)| |(READER BOUNDP-FUNCTION)|
                |SETF PCL DOCUMENTATION| |(READER DIRECT-SUBCLASSES)|
                |(READER DIRECT-SUPERCLASSES)| |(WRITER LAMBDA-LIST)|
                |LISP::LIST class predicate|
                FUNCALLABLE-STANDARD-CLASS-P
                |(FAST-WRITER-METHOD SLOT-OBJECT METHOD)|
                |(BOUNDP CLASS)| |(WRITER SLOT-DEFINITION)|
                |(READER METHODS)| |(READER OPTIONS)|
                |(WRITER CAN-PRECEDE-LIST)|
                |SETF PCL SLOT-DEFINITION-CLASS|
                |SETF PCL SLOT-VALUE-USING-CLASS|
                |(FAST-WRITER-METHOD SLOT-OBJECT DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(FAST-WRITER-METHOD STRUCTURE-SLOT-DEFINITION DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(WRITER PROTOTYPE)| |(BOUNDP TYPE)| |(BOUNDP OBJECT)|
                CLASS-CAN-PRECEDE-LIST |SETF PCL CLASS-DIRECT-SLOTS|
                |SETF PCL CLASS-SLOTS| SLOT-ACCESSOR-FUNCTION
                |(BOUNDP PLIST)|
                |SETF PCL CLASS-INCOMPATIBLE-SUPERCLASS-LIST|
                |SETF PCL SLOT-DEFINITION-WRITERS|
                |(FAST-WRITER-METHOD SLOT-OBJECT SOURCE)|
                |(WRITER DFUN-STATE)| |(WRITER FROM-DEFCLASS-P)|
                |(BOUNDP SLOTS)| SLOT-CLASS-P
                MAKE-READER-METHOD-FUNCTION LEGAL-METHOD-FUNCTION-P
                |(FAST-WRITER-METHOD SLOT-OBJECT INITIALIZE-INFO)|
                |(FAST-WRITER-METHOD SLOT-CLASS INITIALIZE-INFO)|
                |(FAST-WRITER-METHOD SLOT-OBJECT ARG-INFO)|
                |PCL::PLIST-MIXIN class predicate|
                |(WRITER FAST-FUNCTION)| |(WRITER METHOD-CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT WRAPPER)|
                |(WRITER INTERNAL-WRITER-FUNCTION)|
                |(WRITER INTERNAL-READER-FUNCTION)|
                |(WRITER METHOD-COMBINATION)| GET-METHOD
                |(WRITER DIRECT-SLOTS)| |(WRITER DIRECT-METHODS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITARGS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION INITARGS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT OPERATOR)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-WRITER-METHOD STRUCTURE-CLASS DEFSTRUCT-CONSTRUCTOR)|
                |(WRITER BOUNDP-FUNCTION)| |(WRITER DIRECT-SUBCLASSES)|
                |(WRITER DIRECT-SUPERCLASSES)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CLASS-EQ-SPECIALIZER)|
                |(WRITER METHODS)| |(WRITER OPTIONS)|
                SHORT-METHOD-COMBINATION-P GF-ARG-INFO
                SPECIALIZER-METHOD-TABLE MAKE-METHOD-INITARGS-FORM
                CLASS-DEFSTRUCT-FORM |LISP::INTEGER class predicate|
                |(FAST-READER-METHOD SLOT-OBJECT PREDICATE-NAME)|
                |(FAST-READER-METHOD CLASS PREDICATE-NAME)|
                |(FAST-READER-METHOD CLASS NAME)|
                |(FAST-READER-METHOD SLOT-DEFINITION NAME)|
                |(FAST-READER-METHOD SLOT-OBJECT SLOT-NAME)|
                |(FAST-READER-METHOD STANDARD-ACCESSOR-METHOD SLOT-NAME)|
                |(FAST-READER-METHOD SLOT-OBJECT DFUN-STATE)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION DFUN-STATE)|
                |(FAST-READER-METHOD SLOT-OBJECT NAME)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION NAME)|
                GF-PRETTY-ARGLIST SAME-SPECIALIZER-P
                SLOT-DEFINITION-BOUNDP-FUNCTION
                SLOT-DEFINITION-WRITER-FUNCTION
                SLOT-DEFINITION-READER-FUNCTION
                SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION
                SLOT-DEFINITION-INTERNAL-READER-FUNCTION
                |(FAST-READER-METHOD SLOT-OBJECT CLASS)|
                |(FAST-READER-METHOD SLOT-DEFINITION CLASS)|
                |(FAST-READER-METHOD SLOT-OBJECT ACCESSOR-FLAGS)|
                |(FAST-READER-METHOD SLOT-OBJECT METHOD-CLASS)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION METHOD-CLASS)|
                |(FAST-READER-METHOD TRACED-METHOD GENERIC-FUNCTION)|
                |(FAST-READER-METHOD TRACED-METHOD FUNCTION)|
                |(FAST-READER-METHOD LONG-METHOD-COMBINATION FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT INITFUNCTION)|
                |(FAST-READER-METHOD SLOT-DEFINITION INITFUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT ALLOCATION)|
                |(FAST-READER-METHOD STANDARD-SLOT-DEFINITION ALLOCATION)|
                |(FAST-READER-METHOD SLOT-OBJECT INTERNAL-WRITER-FUNCTION)|
                |(FAST-READER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-WRITER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT INTERNAL-READER-FUNCTION)|
                |(FAST-READER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-READER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT BOUNDP-FUNCTION)|
                |(FAST-READER-METHOD EFFECTIVE-SLOT-DEFINITION BOUNDP-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT WRITER-FUNCTION)|
                |(FAST-READER-METHOD EFFECTIVE-SLOT-DEFINITION WRITER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT READER-FUNCTION)|
                |(FAST-READER-METHOD EFFECTIVE-SLOT-DEFINITION READER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT LOCATION)|
                |(FAST-READER-METHOD STANDARD-EFFECTIVE-SLOT-DEFINITION LOCATION)|
                |(FAST-READER-METHOD SLOT-OBJECT FAST-FUNCTION)|
                |(FAST-READER-METHOD STANDARD-METHOD FAST-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT GENERIC-FUNCTION)|
                |(FAST-READER-METHOD STANDARD-METHOD GENERIC-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT SLOT-DEFINITION)|
                |(FAST-READER-METHOD STANDARD-ACCESSOR-METHOD SLOT-DEFINITION)|
                |(FAST-READER-METHOD SLOT-OBJECT METHOD-COMBINATION)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION METHOD-COMBINATION)|
                |(FAST-READER-METHOD SLOT-OBJECT DOCUMENTATION)|
                |(FAST-READER-METHOD STANDARD-METHOD-COMBINATION DOCUMENTATION)|
                |(FAST-READER-METHOD SLOT-OBJECT WRITERS)|
                |(FAST-READER-METHOD SLOT-DEFINITION WRITERS)|
                |(FAST-READER-METHOD SLOT-OBJECT READERS)|
                |(FAST-READER-METHOD SLOT-DEFINITION READERS)|
                |(FAST-READER-METHOD SLOT-OBJECT SPECIALIZERS)|
                |(FAST-READER-METHOD STANDARD-METHOD SPECIALIZERS)|
                |(FAST-READER-METHOD SPECIALIZER TYPE)|
                |(FAST-READER-METHOD SLOT-OBJECT PROTOTYPE)|
                |(FAST-READER-METHOD PCL-CLASS PROTOTYPE)|
                |(FAST-READER-METHOD SLOT-DEFINITION TYPE)|
                |(FAST-READER-METHOD SLOT-OBJECT TYPE)|
                |(FAST-READER-METHOD STANDARD-METHOD-COMBINATION TYPE)|
                |(FAST-READER-METHOD SHORT-METHOD-COMBINATION IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-READER-METHOD SLOT-OBJECT IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-READER-METHOD CLASS-EQ-SPECIALIZER OBJECT)|
                |(FAST-READER-METHOD CLASS-PROTOTYPE-SPECIALIZER OBJECT)|
                |(FAST-READER-METHOD SLOT-OBJECT OBJECT)|
                |(FAST-READER-METHOD EQL-SPECIALIZER OBJECT)|
                |(FAST-READER-METHOD SLOT-OBJECT DEFSTRUCT-FORM)|
                |(FAST-READER-METHOD STRUCTURE-CLASS DEFSTRUCT-FORM)|
                |(FAST-READER-METHOD SLOT-OBJECT INITFORM)|
                |(FAST-READER-METHOD SLOT-DEFINITION INITFORM)|
                |(FAST-READER-METHOD SLOT-OBJECT ARGUMENTS-LAMBDA-LIST)|
                |(FAST-READER-METHOD LONG-METHOD-COMBINATION ARGUMENTS-LAMBDA-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT PLIST)|
                |(FAST-READER-METHOD PLIST-MIXIN PLIST)|
                |(FAST-READER-METHOD SLOT-OBJECT INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-READER-METHOD PCL-CLASS INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT CAN-PRECEDE-LIST)|
                |(FAST-READER-METHOD PCL-CLASS CAN-PRECEDE-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT CLASS-PRECEDENCE-LIST)|
                |(FAST-READER-METHOD PCL-CLASS CLASS-PRECEDENCE-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT LAMBDA-LIST)|
                |(FAST-READER-METHOD STANDARD-METHOD LAMBDA-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT PRETTY-ARGLIST)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION PRETTY-ARGLIST)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-METHODS)|
                |(FAST-READER-METHOD SLOT-OBJECT SLOTS)|
                |(FAST-READER-METHOD SLOT-CLASS SLOTS)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-SLOTS)|
                |(FAST-READER-METHOD SLOT-CLASS DIRECT-SLOTS)|
                |(FAST-READER-METHOD SLOT-OBJECT METHODS)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION METHODS)|
                |(FAST-READER-METHOD SLOT-OBJECT OPTIONS)|
                |(FAST-READER-METHOD STANDARD-METHOD-COMBINATION OPTIONS)|
                |(FAST-READER-METHOD SLOT-OBJECT FROM-DEFCLASS-P)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-SUBCLASSES)|
                |(FAST-READER-METHOD CLASS DIRECT-SUBCLASSES)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-SUPERCLASSES)|
                |(FAST-READER-METHOD CLASS DIRECT-SUPERCLASSES)|
                SLOT-DEFINITION-CLASS EQL-SPECIALIZER-OBJECT
                |PCL::DIRECT-SLOT-DEFINITION class predicate|
                CLASS-CONSTRUCTORS |(BOUNDP WRAPPER)| SLOTS-TO-INSPECT
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PREDICATE-NAME)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SLOT-NAME)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DFUN-STATE)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT NAME)|
                |(BOUNDP DEFSTRUCT-ACCESSOR-SYMBOL)|
                SPECIALIZER-DIRECT-GENERIC-FUNCTIONS
                |(BOUNDP CLASS-EQ-SPECIALIZER)|
                |(SETF SLOT-DEFINITION-NAME)| ADD-WRITER-METHOD
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CLASS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ACCESSOR-FLAGS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT METHOD-CLASS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITFUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ALLOCATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INTERNAL-WRITER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INTERNAL-READER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT BOUNDP-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT WRITER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT READER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT LOCATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT FAST-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT GENERIC-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SLOT-DEFINITION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT METHOD-COMBINATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DOCUMENTATION)|
                |(BOUNDP OPERATOR)| |(BOUNDP ARG-INFO)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT WRITERS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT READERS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SPECIALIZERS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PROTOTYPE)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT TYPE)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT OBJECT)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DEFSTRUCT-FORM)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITFORM)|
                |(SETF SLOT-VALUE-USING-CLASS)|
                |(SETF SLOT-DEFINITION-CLASS)|
                |(SETF SLOT-ACCESSOR-FUNCTION)|
                |(SETF SLOT-DEFINITION-INITFUNCTION)|
                |(SETF SLOT-DEFINITION-ALLOCATION)|
                |(SETF SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-BOUNDP-FUNCTION)|
                |(SETF SLOT-DEFINITION-WRITER-FUNCTION)|
                |(SETF SLOT-DEFINITION-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-LOCATION)|
                |(BOUNDP DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ARGUMENTS-LAMBDA-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PLIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CAN-PRECEDE-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CLASS-PRECEDENCE-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT LAMBDA-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PRETTY-ARGLIST)|
                |(SETF SLOT-DEFINITION-WRITERS)|
                |(SETF SLOT-DEFINITION-READERS)|
                |(SETF SLOT-DEFINITION-TYPE)|
                |(SETF SLOT-DEFINITION-INITFORM)|
                |(BOUNDP INITIALIZE-INFO)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT FROM-DEFCLASS-P)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-METHODS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SLOTS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-SLOTS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT METHODS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT OPTIONS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-SUBCLASSES)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-SUPERCLASSES)|
                |(FAST-INTERNAL-READER-METHOD STANDARD-GENERIC-FUNCTION ARG-INFO)|
                |(BOUNDP INITARGS)| LONG-METHOD-COMBINATION-FUNCTION
                GENERIC-FUNCTION-P
                |PCL::SLOT-DEFINITION class predicate|
                |LISP::NULL class predicate| |(READER NAME)|
                LONG-METHOD-COMBINATION-ARGUMENTS-LAMBDA-LIST
                |(READER CLASS)|
                |(FAST-METHOD (SETF SLOT-ACCESSOR-FUNCTION) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
                |(FAST-METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
                |(FAST-METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
                |(FAST-METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
                |(FAST-METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-ACCESSOR-METHOD T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD :AROUND (GENERIC-FUNCTION METHOD-COMBINATION T))|
                |(FAST-METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS (STANDARD-OBJECT T T T))|
                |(FAST-METHOD DEFAULT-INITARGS (SLOT-CLASS T))|
                |(FAST-METHOD DESCRIBE-OBJECT (T T))|
                |(FAST-METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
                |(FAST-METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
                |(FAST-METHOD DESCRIBE-OBJECT (CLASS T))|
                |(FAST-METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES (GENERIC-FUNCTION T))|
                |(FAST-METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (SLOT-CLASS T))|
                |(FAST-METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
                |(FAST-METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
                |(FAST-METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(FAST-METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(FAST-METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
                |(FAST-METHOD PRINT-OBJECT (T T))|
                |(FAST-METHOD PRINT-OBJECT (CLASS T))|
                |(FAST-METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
                |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD-COMBINATION T))|
                |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
                |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD T))|
                |(FAST-METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
                |(FAST-METHOD LEGAL-DOCUMENTATION-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
                |(FAST-METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
                |(FAST-METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
                |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
                |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
                |(FAST-METHOD UPDATE-GF-DFUN (STD-CLASS T))|
                |(FAST-METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND (STRUCTURE-CLASS T))|
                |(FAST-METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
                |(FAST-METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
                |(FAST-METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
                |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (SLOT-CLASS T))|
                |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (SLOT-CLASS T))|
                |(FAST-METHOD MAKE-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T))|
                |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
                |(FAST-METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
                |(FAST-METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|
                |(FAST-METHOD SLOT-UNBOUND (T T T))|
                |(FAST-METHOD FIND-METHOD-COMBINATION (GENERIC-FUNCTION (EQL STANDARD) T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
                |(FAST-METHOD (SETF SLOT-ACCESSOR-STD-P) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD COMPUTE-SLOT-ACCESSOR-INFO (EFFECTIVE-SLOT-DEFINITION T T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (DOCUMENTATION-MIXIN T))|
                |(FAST-METHOD (SETF DOCUMENTATION) (T T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
                |(FAST-METHOD READER-METHOD-CLASS (SLOT-CLASS T))|
                |(FAST-METHOD WRITER-METHOD-CLASS (SLOT-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
                |(FAST-METHOD REMOVE-NAMED-METHOD (T T))|
                |(FAST-METHOD FIND-METHOD (STANDARD-GENERIC-FUNCTION T T))|
                |(FAST-METHOD SLOT-MISSING (T T T T))|
                LEGAL-SLOT-NAME-P |(READER TYPE)| |(READER OBJECT)|
                CLASS-WRAPPER |(READER PLIST)|
                |(FAST-METHOD NO-APPLICABLE-METHOD (T))|
                |(FAST-METHOD DOCUMENTATION (T))|
                |(FAST-METHOD CLASS-PREDICATE-NAME (T))|
                |(READER SLOTS)| |(WRITER NAME)| DEFINITION-SOURCE
                |PCL::SLOT-OBJECT class predicate| DEFAULT-INITARGS
                |(WRITER CLASS)| CLASS-SLOT-VALUE |(WRITER TYPE)|
                |(WRITER OBJECT)|
                |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
                |(WRITER PLIST)| |(WRITER SLOTS)|
                |PCL::DOCUMENTATION-MIXIN class predicate|
                FORWARD-REFERENCED-CLASS-P GF-FAST-METHOD-FUNCTION-P
                |LISP::REAL class predicate| LEGAL-QUALIFIER-P METHOD-P
                |(COMBINED-METHOD COMPUTE-EFFECTIVE-METHOD)|
                NO-PRIMARY-METHOD
                |PCL::SPECIALIZER-WITH-OBJECT class predicate|
                CLASS-SLOT-CELLS
                |(COMBINED-METHOD INITIALIZE-INSTANCE)|
                |(COMBINED-METHOD REINITIALIZE-INSTANCE)|
                STANDARD-ACCESSOR-METHOD-P |(SETF CLASS-NAME)|
                STANDARD-GENERIC-FUNCTION-P STANDARD-READER-METHOD-P
                STANDARD-METHOD-P |(READER WRAPPER)|
                |(READER DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(READER CLASS-EQ-SPECIALIZER)|
                COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS
                COMPUTE-DEFAULT-INITARGS |(SETF CLASS-DEFSTRUCT-FORM)|
                |(CALL REAL-MAKE-METHOD-LAMBDA)|
                |(SETF CLASS-INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL CLASS-SLOT-VALUE| |(SETF CLASS-SLOTS)|
                |(SETF CLASS-DIRECT-SLOTS)| |(READER OPERATOR)|
                |(CALL REAL-GET-METHOD)| |(CALL REAL-REMOVE-METHOD)|
                |(CALL REAL-ADD-METHOD)| |(READER ARG-INFO)|
                METHOD-COMBINATION-TYPE
                |(READER DEFSTRUCT-CONSTRUCTOR)|
                |(INTERNAL-READER-METHOD STANDARD-GENERIC-FUNCTION ARG-INFO)|
                |(READER INITIALIZE-INFO)| |(WRITER WRAPPER)|
                STANDARD-CLASS-P |LISP::NUMBER class predicate|
                LEGAL-SPECIALIZER-P
                |PCL::LONG-METHOD-COMBINATION class predicate|
                |(WRITER DEFSTRUCT-ACCESSOR-SYMBOL)|
                COMPUTE-SLOT-ACCESSOR-INFO |(READER INITARGS)|
                |(WRITER CLASS-EQ-SPECIALIZER)|
                STANDARD-BOUNDP-METHOD-P |(SETF DOCUMENTATION)|
                RAW-INSTANCE-ALLOCATOR
                |SETF PCL SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL|
                |SETF PCL CLASS-INITIALIZE-INFO| |(WRITER OPERATOR)|
                |(WRITER ARG-INFO)|
                COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO
                STANDARD-WRITER-METHOD-P
                CLASS-INCOMPATIBLE-SUPERCLASS-LIST
                |(WRITER DEFSTRUCT-CONSTRUCTOR)|
                |PCL::TRACED-METHOD class predicate| WRAPPER-FETCHER
                MAKE-A-METHOD |(WRITER INITIALIZE-INFO)|
                METHOD-COMBINATION-DOCUMENTATION
                |SETF PCL SLOT-DEFINITION-INITARGS|
                REMOVE-BOUNDP-METHOD ADD-NAMED-METHOD
                |LISP::CONS class predicate|
                |SETF PCL CLASS-DEFSTRUCT-CONSTRUCTOR|
                |(WRITER INITARGS)| |(BOUNDP METHOD)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PREDICATE-NAME)|
                |(FAST-WRITER-METHOD CLASS NAME)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION NAME)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SLOT-NAME)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DFUN-STATE)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION DFUN-STATE)|
                |(FAST-WRITER-METHOD SLOT-OBJECT NAME)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION NAME)|
                |(BOUNDP SOURCE)| |(SETF GF-DFUN-STATE)|
                SHORT-COMBINATION-OPERATOR
                |(FAST-WRITER-METHOD SLOT-OBJECT CLASS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT ACCESSOR-FLAGS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHOD-CLASS)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION METHOD-CLASS)|
                |(FAST-WRITER-METHOD TRACED-METHOD GENERIC-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITFUNCTION)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION INITFUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT ALLOCATION)|
                |(FAST-WRITER-METHOD STANDARD-SLOT-DEFINITION ALLOCATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INTERNAL-WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INTERNAL-READER-FUNCTION)|
                |(FAST-WRITER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-READER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT BOUNDP-FUNCTION)|
                |(FAST-WRITER-METHOD EFFECTIVE-SLOT-DEFINITION BOUNDP-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD EFFECTIVE-SLOT-DEFINITION WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT READER-FUNCTION)|
                |(FAST-WRITER-METHOD EFFECTIVE-SLOT-DEFINITION READER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT LOCATION)|
                |(FAST-WRITER-METHOD STANDARD-EFFECTIVE-SLOT-DEFINITION LOCATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT FAST-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT GENERIC-FUNCTION)|
                |(FAST-WRITER-METHOD STANDARD-METHOD GENERIC-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SLOT-DEFINITION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHOD-COMBINATION)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION METHOD-COMBINATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DOCUMENTATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT WRITERS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION WRITERS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT READERS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION READERS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SPECIALIZERS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PROTOTYPE)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION TYPE)|
                |(FAST-WRITER-METHOD SLOT-OBJECT TYPE)|
                |(FAST-WRITER-METHOD SLOT-OBJECT IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-WRITER-METHOD SLOT-OBJECT OBJECT)|
                REMOVE-NAMED-METHOD
                |(FAST-WRITER-METHOD SLOT-OBJECT DEFSTRUCT-FORM)|
                |(FAST-WRITER-METHOD STRUCTURE-CLASS DEFSTRUCT-FORM)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITFORM)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION INITFORM)|
                |(FAST-WRITER-METHOD SLOT-OBJECT ARGUMENTS-LAMBDA-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PLIST)|
                |(FAST-WRITER-METHOD PLIST-MIXIN PLIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-WRITER-METHOD PCL-CLASS INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CAN-PRECEDE-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CLASS-PRECEDENCE-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT LAMBDA-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PRETTY-ARGLIST)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION PRETTY-ARGLIST)|
                LEGAL-DOCUMENTATION-P CLASS-DIRECT-SUPERCLASSES
                CLASS-DIRECT-SUBCLASSES CLASS-DIRECT-DEFAULT-INITARGS
                SLOT-DEFINITION-READERS SLOT-VALUE-USING-CLASS
                COMPUTE-APPLICABLE-METHODS CLASS-NAME CLASS-PROTOTYPE
                READER-METHOD-CLASS REMOVE-METHOD
                SLOT-DEFINITION-INITFORM
                UPDATE-INSTANCE-FOR-REDEFINED-CLASS
                UPDATE-INSTANCE-FOR-DIFFERENT-CLASS CHANGE-CLASS
                METHOD-FUNCTION DIRECT-SLOT-DEFINITION-CLASS
                MAKE-METHOD-LAMBDA EFFECTIVE-SLOT-DEFINITION-CLASS
                CLASS-SLOTS COMPUTE-SLOTS SLOT-DEFINITION-NAME
                FINALIZE-INHERITANCE
                GENERIC-FUNCTION-ARGUMENT-PRECEDENCE-ORDER
                GENERIC-FUNCTION-LAMBDA-LIST NO-NEXT-METHOD
                CLASS-DIRECT-SLOTS CLASS-DEFAULT-INITARGS
                COMPUTE-DISCRIMINATING-FUNCTION CLASS-FINALIZED-P
                GENERIC-FUNCTION-NAME REMOVE-DEPENDENT
                COMPUTE-CLASS-PRECEDENCE-LIST ADD-DEPENDENT
                SLOT-BOUNDP-USING-CLASS ACCESSOR-METHOD-SLOT-DEFINITION
                SHARED-INITIALIZE ADD-DIRECT-METHOD
                SLOT-DEFINITION-LOCATION SLOT-DEFINITION-INITFUNCTION
                SLOT-DEFINITION-ALLOCATION ADD-METHOD
                GENERIC-FUNCTION-METHOD-CLASS METHOD-SPECIALIZERS
                SLOT-DEFINITION-INITARGS WRITER-METHOD-CLASS
                ADD-DIRECT-SUBCLASS SPECIALIZER-DIRECT-METHODS
                GENERIC-FUNCTION-METHOD-COMBINATION ALLOCATE-INSTANCE
                COMPUTE-EFFECTIVE-METHOD SLOT-DEFINITION-TYPE
                SLOT-UNBOUND INITIALIZE-INSTANCE FIND-METHOD
                FUNCTION-KEYWORDS REINITIALIZE-INSTANCE
                VALIDATE-SUPERCLASS GENERIC-FUNCTION-METHODS
                REMOVE-DIRECT-METHOD METHOD-LAMBDA-LIST MAKE-INSTANCE
                GENERIC-FUNCTION-DECLARATIONS
                COMPUTE-EFFECTIVE-SLOT-DEFINITION PRINT-OBJECT
                METHOD-QUALIFIERS METHOD-GENERIC-FUNCTION
                REMOVE-DIRECT-SUBCLASS MAKE-INSTANCES-OBSOLETE
                SLOT-MAKUNBOUND-USING-CLASS
                ENSURE-GENERIC-FUNCTION-USING-CLASS SLOT-MISSING
                MAP-DEPENDENTS UPDATE-DEPENDENT FIND-METHOD-COMBINATION
                ENSURE-CLASS-USING-CLASS NO-APPLICABLE-METHOD
                SLOT-DEFINITION-WRITERS
                COMPUTE-APPLICABLE-METHODS-USING-CLASSES
                CLASS-PRECEDENCE-LIST))
  (SETF (GET V 'COMPILER::PROCLAIMED-CLOSURE) T)) 
