#!/bin/sh
# maintain link from old to new location for docs.
if [ "$1" = "configure" ]; then
 if [ -d /usr/doc -a ! -e /usr/doc/libgmp3 -a -d /usr/share/doc/libgmp3 ]; then
  ln -sf ../share/doc/libgmp3 /usr/doc/libgmp3
 fi
# Transition documentation to its own package
  if [ ! -e /usr/share/doc/libgmp3-doc -a -e /usr/share/info/gmp.info.gz ]; then
    rm -f /usr/share/info/gmp.info*
  fi
set -e
ldconfig
fi
