#!/bin/sh
if [ \( "$1" = "upgrade" -o "$1" = "remove" -o "$1" = "purge" \) ]; then 
# Cruft removal
  if [ -L /usr/doc/libgmp3 ]; then
    rm -f /usr/doc/libgmp3
  fi
  if [ -L /usr/info/gmp3.info.gz ]; then
    rm -f /usr/info/gmp3.info.gz
  fi
  if [ -L /usr/info/gmp3.info ]; then
    rm -f /usr/info/gmp3.info
  fi
fi
