# a facility for displaying DOC files and completing on them
# requires gnu emacs, to be in the search path

# A directory on peoples search path.


ELISP=gcl.el dbl.el ansi-doc.el lisp-complete.el sshell.el

-include ../makedefs
